PROCEDURES = (
    {"id": "blepharoplasty", "region": "eyes", "name_th": "ศัลยกรรมเปลือกตา", "name_en": "Blepharoplasty", "simulation": True, "summary_th": "ข้อมูลเพื่อทำความเข้าใจการเปลี่ยนแปลงบริเวณเปลือกตา ไม่ใช่คำแนะนำให้ผ่าตัด", "limitations_th": "ภาพไม่แสดงแผลเป็น การหายของแผล หรือการทำงานของเปลือกตา", "source": "https://www.plasticsurgery.org/cosmetic-procedures/eyelid-surgery"},
    {"id": "rhinoplasty-open", "region": "nose", "name_th": "ศัลยกรรมจมูกแบบเปิด", "name_en": "Open rhinoplasty", "simulation": True, "summary_th": "Open หมายถึงวิธีเข้าถึงโครงสร้าง ไม่ใช่ทรงจมูก", "limitations_th": "ภาพจำลองไม่สามารถประเมินกระดูกอ่อน ผิว ทางเดินหายใจ หรือการหายของแต่ละคน", "source": "https://www.plasticsurgery.org/cosmetic-procedures/rhinoplasty"},
    {"id": "rhinoplasty-closed", "region": "nose", "name_th": "ศัลยกรรมจมูกแบบปิด", "name_en": "Closed rhinoplasty", "simulation": True, "summary_th": "Closed หมายถึงแผลผ่าตัดอยู่ภายในจมูกและไม่ได้กำหนดทรงผลลัพธ์", "limitations_th": "แพทย์ต้องประเมินวิธีที่เหมาะสมจากกายวิภาคจริง", "source": "https://www.plasticsurgery.org/cosmetic-procedures/rhinoplasty"},
    {"id": "lip-lift", "region": "lips", "name_th": "ศัลยกรรมยกริมฝีปาก", "name_en": "Lip lift", "simulation": True, "summary_th": "ภาพประกอบการเปลี่ยนระยะริมฝีปากเท่านั้น", "limitations_th": "ไม่แสดงแผลเป็น การเคลื่อนไหว หรือผลการหาย", "source": "https://www.plasticsurgery.org/cosmetic-procedures/lip-augmentation"},
    {"id": "lip-reduction", "region": "lips", "name_th": "ศัลยกรรมลดริมฝีปาก", "name_en": "Lip reduction", "simulation": True, "summary_th": "ภาพประกอบความเปลี่ยนแปลงของความสูงและความอิ่มริมฝีปาก", "limitations_th": "ไม่สามารถทำนายการเคลื่อนไหวหรือแผลเป็น", "source": "https://www.plasticsurgery.org/cosmetic-procedures/lip-augmentation"},
    {"id": "cheek-augmentation", "region": "cheeks", "name_th": "ศัลยกรรมเสริมแก้ม", "name_en": "Cheek augmentation", "simulation": True, "summary_th": "ภาพประกอบ projection และ volume ภายนอก", "limitations_th": "ไม่เลือกชนิดหรือตำแหน่งวัสดุให้ผู้ใช้", "source": "https://www.plasticsurgery.org/cosmetic-procedures/cheek-augmentation"},
    {"id": "buccal-fat-removal", "region": "cheeks", "name_th": "ผ่าตัดไขมันกระพุ้งแก้ม", "name_en": "Buccal fat removal", "simulation": False, "summary_th": "ข้อมูลเพื่อเตรียมคำถามสำหรับแพทย์", "limitations_th": "ไม่จำลองเพราะผลระยะยาวและกายวิภาคชั้นลึกประเมินจากภาพไม่ได้", "source": "https://www.plasticsurgery.org/cosmetic-procedures/buccal-fat-removal"},
    {"id": "jaw-contouring", "region": "jaw", "name_th": "ศัลยกรรมปรับแนวกราม", "name_en": "Jaw contouring", "simulation": True, "summary_th": "ภาพประกอบ contour ภายนอก ไม่ใช่แบบวางแผนกระดูก", "limitations_th": "ไม่ประเมินการสบฟัน เส้นประสาท หรือทางเดินหายใจ", "source": "https://www.plasticsurgery.org/cosmetic-procedures/facial-implants"},
    {"id": "orthognathic-surgery", "region": "jaw", "name_th": "ศัลยกรรมขากรรไกร", "name_en": "Orthognathic surgery", "simulation": False, "summary_th": "ข้อมูลทั่วไปเท่านั้นและต้องประเมินโดยทีมศัลยแพทย์/ทันตแพทย์", "limitations_th": "ไม่จำลองหรือแนะนำจากภาพใบหน้า", "source": "https://www.aaoms.org/conditions-and-treatments/orthognathic-surgery"},
    {"id": "genioplasty", "region": "chin", "name_th": "ศัลยกรรมปรับกระดูกคาง", "name_en": "Genioplasty", "simulation": True, "summary_th": "ภาพประกอบ projection/height/width ภายนอก", "limitations_th": "ไม่ใช่การวางแผนกระดูกและไม่แสดงเส้นประสาทหรือการสบฟัน", "source": "https://www.plasticsurgery.org/cosmetic-procedures/facial-implants"},
    {"id": "chin-implant", "region": "chin", "name_th": "เสริมคางด้วยวัสดุ", "name_en": "Chin implant", "simulation": True, "summary_th": "ภาพประกอบมิติภายนอกเท่านั้น", "limitations_th": "ไม่เลือกขนาดหรือตำแหน่งวัสดุ", "source": "https://www.plasticsurgery.org/cosmetic-procedures/facial-implants"},
)
