export type Locale = "th" | "en";
export type Market = "TH" | "GLOBAL";

export const siteCopy = {
  en: {
    nav: ["Product", "Research", "Safety", "Clinics", "Pricing"],
    start: "Start my analysis",
    sample: "See sample analysis",
    hero: "Your appearance is part of every first impression.",
    heroBody:
      "Understand it. Invest in yourself. Improve with intention. We analyze your face to show what matters most and build a personalized path beyond generic advice.",
    assurances: [
      "Secure processing",
      "85+ facial measurements",
      "Your data stays private",
    ],
    analysisTitle: "You can’t improve what you can’t see.",
    analysisBody:
      "We map 80+ facial measurements to reveal your proportions, balance, and highest-impact opportunities.",
    interactive: "Interactive sample · Hover or tap a metric",
    safetyTitle: "Built for informed decisions, not pressure.",
    safety: [
      [
        "Secure processing",
        "Your data stays private with clear user control and consent.",
      ],
      [
        "Transparent scoring",
        "See the factors, weighting and limits behind the result.",
      ],
      [
        "Preview limitations",
        "Possibilities, not promises, predictions or guarantees.",
      ],
      [
        "Shareable consultation report",
        "Bring your analysis, goals and questions into a professional consultation.",
      ],
    ],
    pricingTitle: "Start with clarity.\nKeep improving every month.",
    pricingBody:
      "Start free, then upgrade for ongoing analysis, previews and progress tracking.",
    freeTitle: "Free analysis",
    freeBody: "A useful first look across your key factors.",
    freeFeatures: [
      "Basic factor analysis",
      "Top improvement priorities",
      "One preview direction",
    ],
    startFree: "Start free",
    completeTitle: "Complete plan",
    membership: "Monthly membership",
    completeBody: "Ongoing guidance that evolves with your goals and progress.",
    completeFeatures: [
      "Full 85+ factor analysis",
      "Monthly progress reassessment",
      "New illustrative previews",
      "Shareable consultation report",
    ],
    startMonthly: "Start monthly plan",
    cancel: "Cancel anytime.",
    forYou: "For you",
    userCtaTitle: "Build a plan for your face.",
    userCtaBody: "Understand. Preview. Decide.",
    forClinics: "For clinics",
    clinicCtaTitle: "Bring 3D into the consultation.",
    clinicCtaBody: "Join the early clinic program.",
    joinPilot: "Join the pilot",
    footer: "Educational analysis only. Not medical advice.",
    about: {
      label: "About us",
      title: "Meet DOODEE",
      body: "DOODEE is an AI pre-consultation companion for facial assessment. It helps you understand your own proportions and arrive at a clinic with informed questions.",
      values: [
        [
          "Objective assessment",
          "Structure and proportion read from anatomical landmarks, with no sales pressure attached to the result.",
        ],
        [
          "Privacy by design",
          "Images live in a private bucket behind expiring signed links, and are processed only to build your report.",
        ],
        [
          "Your own features",
          "The analysis surfaces what is distinctive about your face and what is worth asking a clinician, not a single template to converge on.",
        ],
      ],
      bannerLabel: "Why check first?",
      bannerTitle: "Less hesitation, more value from every consultation",
      bannerBody:
        "A procedure decision made on a vague feeling becomes a decision made on measurements you can point at and question.",
    },
    data: {
      label: "Data we use",
      title: "Transparent about what is measured, and what is not",
      body: "DOODEE reads facial geometry to build a clear, non-judgmental report. Every limitation below is stated rather than hidden.",
      items: [
        [
          "2D landmark ratios",
          "Ratios measured within a single image from facial landmarks. No millimetre calibration, and no Golden Ratio beauty score.",
        ],
        [
          "Skin tone and texture signals",
          "Visible tone evenness, redness and texture, read under the lighting limits of your own photo.",
        ],
        [
          "Thai photographic reference",
          "Experimental comparison against mean and SD from 240 Thai adults aged 18–35. A reference population, not a beauty standard.",
        ],
        [
          "Private storage",
          "A private bucket with expiring signed links. Adult scans expire after 30 days; minors' after 24 hours.",
        ],
      ],
      guaranteeTitle: "What we commit to",
      guarantees: [
        "Your face images are never sold or shared with third parties.",
        "Images are processed only to generate your own report.",
        "You can delete your scan history, or your whole account, at any time.",
      ],
    },
    contact: {
      label: "Contact us",
      title: "We are here to help",
      body: "Whether you use DOODEE yourself, run a clinic, or want to partner with us, the team reads every message.",
      channelsTitle: "Direct channels",
      lineLabel: "LINE Official Account",
      emailLabel: "Email support",
      partnerLabel: "Clinic partnership",
      hoursTitle: "Support hours",
      hours: "Mon–Fri 09:00–18:00 (ICT)",
      write: "Write to us",
    },
    login: {
      back: "Back to home",
      titleLead: "Sign in to",
      google: "Continue with Google",
      googleBusy: "Connecting...",
      preparing: "Preparing your experience",
      preparingBody: "Setting up your personal analysis",
      referralToggle: "Have a referral code?",
      referralLabel: "Referral code",
      referralPlaceholder: "Enter code",
      apply: "Apply",
      referralIdle: "Your code will be linked to this account.",
      referralTooShort: "Enter your referral code.",
      referralSaved: "Referral code applied.",
      legalLead: "By continuing, you agree to the",
      terms: "Terms",
      legalMid: "and acknowledge the",
      privacy: "Privacy Policy",
      signInFailed: "Could not sign in. Please try again.",
      tabSignIn: "Sign in",
      tabSignUp: "Create account",
      or: "or",
      email: "Email",
      emailPlaceholder: "you@example.com",
      password: "Password",
      passwordPlaceholder: "At least 8 characters",
      submitSignIn: "Sign in",
      submitSignUp: "Create account",
      busy: "Please wait...",
      forgot: "Forgot your password?",
      resetSent: "If that email has an account, a reset link is on its way.",
      showPassword: "Show password",
      hidePassword: "Hide password",
      errEmail: "Enter a valid email address.",
      errShort: "Password must be at least 8 characters.",
      errEmailInUse: "That email already has an account. Sign in instead.",
      errInvalidEmail: "That email address is not valid.",
      errWeakPassword: "That password is too easy to guess. Try a longer one.",
      errBadCredentials: "Email or password is incorrect.",
      errDisabled: "This account has been suspended. Contact us.",
      errTooMany: "Too many attempts. Wait a moment and try again.",
      errNetwork: "Cannot reach the server. Check your connection.",
      errPopupClosed: "The Google window was closed before finishing.",
      errMethodDisabled: "Email sign-in is not switched on for this site yet.",
      errGeneric: "Something went wrong. Please try again.",
    },
  },
  th: {
    nav: ["การวิเคราะห์", "งานวิจัย", "มาตรฐาน", "สำหรับคลินิก", "ราคา"],
    start: "เริ่มวิเคราะห์",
    sample: "ดูตัวอย่างผลวิเคราะห์",
    hero: "วิเคราะห์ใบหน้าอย่างเข้าใจ เพื่อการตัดสินใจที่เหมาะกับคุณ",
    heroBody:
      "เราใช้เทคโนโลยีวิเคราะห์โครงสร้างใบหน้าของคุณด้วยข้อมูลเชิงลึก เพื่อให้คุณเข้าใจจุดเด่นและสัดส่วนของใบหน้า พร้อมรับคำแนะนำที่ออกแบบให้เหมาะกับคุณ",
    assurances: [
      "ประมวลผลข้อมูลอย่างปลอดภัย",
      "วิเคราะห์โครงหน้าเชิงลึกกว่า 85 จุด",
      "ข้อมูลปลอดภัย และเป็นส่วนตัว",
    ],
    analysisTitle: "เข้าใจความสมดุลและจุดเด่นบนใบหน้าคุณ",
    analysisBody:
      "เราวิเคราะห์สัดส่วนและองค์ประกอบของใบหน้ามากกว่า 80 จุด เพื่อช่วยให้คุณเข้าใจความสมดุลของใบหน้าและจุดเด่นที่สำคัญ",
    interactive: "ตัวอย่างผลวิเคราะห์ · แตะเพื่อดูรายละเอียด",
    safetyTitle: "ข้อมูลที่ชัดขึ้น เพื่อการตัดสินใจที่เป็นของคุณ",
    safety: [
      [
        "ประมวลผลข้อมูลอย่างปลอดภัย",
        "ข้อมูลของคุณเป็นส่วนตัว พร้อมสิทธิ์ในการควบคุมและการยินยอมที่ชัดเจน",
      ],
      [
        "เข้าใจที่มาของคะแนน",
        "ดูปัจจัย น้ำหนัก และข้อจำกัดที่มีผลต่อผลลัพธ์",
      ],
      [
        "ข้อจำกัดของภาพจำลอง",
        "ภาพจำลองแสดงแนวทางที่เป็นไปได้ ไม่ใช่การคาดการณ์หรือการรับประกันผลลัพธ์",
      ],
      [
        "เตรียมตัวก่อนปรึกษาผู้เชี่ยวชาญ",
        "สรุปผลวิเคราะห์ เป้าหมาย และคำถามสำคัญไว้สำหรับการพูดคุย",
      ],
    ],
    pricingTitle: "เห็นภาพชัดขึ้นในวันนี้\nและติดตามความเปลี่ยนแปลงต่อไป",
    pricingBody:
      "เริ่มใช้ฟรี แล้วเลือกอัปเกรดเมื่อคุณต้องการวิเคราะห์เพิ่มเติม ดูภาพจำลอง และติดตามผลอย่างต่อเนื่อง",
    freeTitle: "ผลวิเคราะห์เบื้องต้น",
    freeBody: "ดูภาพรวมเบื้องต้นของใบหน้าคุณ",
    freeFeatures: [
      "จุดวัดหลักที่ส่งผลต่อภาพรวม",
      "ลำดับการพัฒนาที่ควรเริ่มก่อน",
      "ภาพจำลอง 1 แนวทาง",
    ],
    startFree: "เริ่มวิเคราะห์ฟรี",
    completeTitle: "แผนสำหรับคุณ",
    membership: "สมาชิกแบบรายเดือน",
    completeBody:
      "การวิเคราะห์เต็มรูปแบบที่ติดตามเป้าหมายและความเปลี่ยนแปลงของคุณในทุกเดือน",
    completeFeatures: [
      "ผลวิเคราะห์มากกว่า 85 จุด",
      "เปรียบเทียบพัฒนาการรายเดือน",
      "สำรวจภาพจำลองเพิ่มเติม",
      "รายงานพร้อมใช้ก่อนเข้าปรึกษา",
    ],
    startMonthly: "เลือก Complete",
    cancel: "ยกเลิกได้ทุกเมื่อ",
    forYou: "สำหรับคุณ",
    userCtaTitle: "รู้ว่าควรเริ่มตรงไหนบนใบหน้าคุณ",
    userCtaBody: "วิเคราะห์ เห็นภาพ และวางลำดับอย่างชัดเจน",
    forClinics: "สำหรับคลินิก",
    clinicCtaTitle: "สร้างประสบการณ์ปรึกษาที่เห็นภาพด้วย 3D",
    clinicCtaBody: "ให้คนไข้เข้าใจทางเลือกและคุยกับแพทย์ได้ตรงประเด็นขึ้น",
    joinPilot: "ขอเดโมสำหรับคลินิก",
    footer:
      "ผลวิเคราะห์ใช้เพื่อประกอบการตัดสินใจ ไม่ใช่คำวินิจฉัยหรือคำแนะนำทางการแพทย์",
    about: {
      label: "เกี่ยวกับเรา",
      title: "ทำความรู้จักกับ DOODEE",
      body: "DOODEE คือผู้ช่วยประเมินใบหน้าด้วย AI ก่อนเข้าพบแพทย์ เพื่อให้คุณเข้าใจสัดส่วนใบหน้าของตัวเอง และเตรียมคำถามสำคัญไปคุยกับคลินิกได้อย่างมั่นใจ",
      values: [
        [
          "ประเมินอย่างเป็นกลาง",
          "อ่านโครงหน้าและสัดส่วนจากจุดอ้างอิงทางกายวิภาค ผลลัพธ์ไม่ผูกกับการเชียร์ขายคอร์ส",
        ],
        [
          "ออกแบบโดยยึดความเป็นส่วนตัว",
          "ภาพเก็บใน bucket ส่วนตัวและเปิดผ่านลิงก์ชั่วคราว ประมวลผลเพื่อสร้างรายงานของคุณเท่านั้น",
        ],
        [
          "เคารพลักษณะเฉพาะของคุณ",
          "ผลวิเคราะห์ชี้ให้เห็นสิ่งที่เป็นเอกลักษณ์บนใบหน้าคุณและประเด็นที่ควรถามแพทย์ ไม่ใช่แม่แบบเดียวที่ทุกคนต้องเดินเข้าหา",
        ],
      ],
      bannerLabel: "ทำไมต้องเช็กก่อน?",
      bannerTitle: "ลดความลังเล เพิ่มความคุ้มค่าให้ทุกการปรึกษา",
      bannerBody:
        "เปลี่ยนการตัดสินใจที่อิงความรู้สึกไม่แน่นอน ให้เป็นการตัดสินใจบนตัวเลขที่ชี้ได้และตั้งคำถามต่อได้",
    },
    data: {
      label: "ข้อมูลที่เราใช้",
      title: "โปร่งใสว่าวัดอะไร และไม่ได้วัดอะไร",
      body: "DOODEE อ่านเรขาคณิตใบหน้าเพื่อสร้างรายงานที่ชัดเจนและไม่ตัดสิน ข้อจำกัดทุกข้อด้านล่างระบุไว้ตรงๆ ไม่ได้ซ่อน",
      items: [
        [
          "สัดส่วนจาก landmark ภาพ 2D",
          "วัดอัตราส่วนภายในภาพเดียวกันจากจุด landmark บนใบหน้า ไม่แปลงเป็นมิลลิเมตร และไม่ใช้ Golden Ratio เป็นคะแนนความงาม",
        ],
        [
          "สัญญาณโทนสีและพื้นผิวผิว",
          "สังเกตความสม่ำเสมอของโทนสี รอยแดง และพื้นผิวเท่าที่เห็นได้ ภายใต้ข้อจำกัดของแสงในภาพของคุณเอง",
        ],
        [
          "ค่าอ้างอิงจากภาพถ่ายคนไทย",
          "เปรียบเทียบเชิงทดลองกับค่าเฉลี่ยและส่วนเบี่ยงเบนจากคนไทย 240 คน อายุ 18–35 ปี เป็นประชากรอ้างอิง ไม่ใช่เกณฑ์ความสวย",
        ],
        [
          "พื้นที่จัดเก็บส่วนตัว",
          "เก็บใน bucket ส่วนตัวและเปิดด้วยลิงก์ชั่วคราว ภาพผู้ใหญ่หมดอายุใน 30 วัน ผู้เยาว์ 24 ชั่วโมง",
        ],
      ],
      guaranteeTitle: "สิ่งที่เรายึดถือ",
      guarantees: [
        "ไม่ขายหรือแชร์ภาพใบหน้าของคุณให้บุคคลที่สาม",
        "ประมวลผลภาพเพื่อสร้างรายงานของคุณเท่านั้น",
        "ลบประวัติการสแกน หรือลบบัญชีทั้งหมด ได้ทุกเมื่อ",
      ],
    },
    contact: {
      label: "ติดต่อเรา",
      title: "พร้อมพูดคุยและตอบทุกคำถาม",
      body: "ไม่ว่าคุณจะเป็นผู้ใช้งาน คลินิกความงาม หรือสนใจร่วมเป็นพันธมิตร ทีมงาน DOODEE อ่านทุกข้อความ",
      channelsTitle: "ช่องทางติดต่อ",
      lineLabel: "LINE Official Account",
      emailLabel: "อีเมลฝ่ายสนับสนุน",
      partnerLabel: "ร่วมเป็นคลินิกพันธมิตร",
      hoursTitle: "เวลาทำการ",
      hours: "จันทร์–ศุกร์ 09:00–18:00 น. (เว้นวันหยุดนักขัตฤกษ์)",
      write: "ส่งข้อความถึงเรา",
    },
    login: {
      back: "กลับหน้าแรก",
      titleLead: "เข้าสู่ระบบ",
      google: "ดำเนินการต่อด้วย Google",
      googleBusy: "กำลังเชื่อมต่อ...",
      preparing: "กำลังเตรียมพร้อม",
      preparingBody: "กำลังตั้งค่าการวิเคราะห์ของคุณ",
      referralToggle: "มีโค้ดแนะนำเพื่อนไหม?",
      referralLabel: "โค้ดแนะนำเพื่อน",
      referralPlaceholder: "กรอกโค้ด",
      apply: "ใช้โค้ด",
      referralIdle: "โค้ดจะถูกผูกกับบัญชีนี้",
      referralTooShort: "กรอกโค้ดแนะนำเพื่อนของคุณ",
      referralSaved: "ใช้โค้ดแนะนำเพื่อนแล้ว",
      legalLead: "การดำเนินการต่อถือว่าคุณยอมรับ",
      terms: "ข้อกำหนดการใช้งาน",
      legalMid: "และรับทราบ",
      privacy: "นโยบายความเป็นส่วนตัว",
      signInFailed: "เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
      tabSignIn: "เข้าสู่ระบบ",
      tabSignUp: "สมัครสมาชิก",
      or: "หรือ",
      email: "อีเมล",
      emailPlaceholder: "you@example.com",
      password: "รหัสผ่าน",
      passwordPlaceholder: "อย่างน้อย 8 ตัวอักษร",
      submitSignIn: "เข้าสู่ระบบ",
      submitSignUp: "สมัครสมาชิก",
      busy: "กรุณารอสักครู่...",
      forgot: "ลืมรหัสผ่าน?",
      resetSent: "ถ้าอีเมลนี้มีบัญชีอยู่ ลิงก์ตั้งรหัสผ่านใหม่กำลังส่งไป",
      showPassword: "แสดงรหัสผ่าน",
      hidePassword: "ซ่อนรหัสผ่าน",
      errEmail: "กรอกอีเมลให้ถูกต้อง",
      errShort: "รหัสผ่านต้องยาวอย่างน้อย 8 ตัวอักษร",
      errEmailInUse: "อีเมลนี้มีบัญชีอยู่แล้ว กรุณาเข้าสู่ระบบแทน",
      errInvalidEmail: "รูปแบบอีเมลไม่ถูกต้อง",
      errWeakPassword: "รหัสผ่านเดาง่ายเกินไป ลองตั้งให้ยาวขึ้น",
      errBadCredentials: "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
      errDisabled: "บัญชีนี้ถูกระงับ กรุณาติดต่อทีมงาน",
      errTooMany: "ลองผิดหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
      errNetwork: "เชื่อมต่อเซิร์ฟเวอร์ไม่ได้ ตรวจสอบอินเทอร์เน็ตของคุณ",
      errPopupClosed: "หน้าต่าง Google ถูกปิดก่อนเสร็จ",
      errMethodDisabled: "ยังไม่ได้เปิดการสมัครด้วยอีเมลสำหรับเว็บนี้",
      errGeneric: "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
    },
  },
} as const;
