import {
  CATALOG_MEASURED, CATALOG_TOTAL, MEASURED_METRICS, PLAN_LIMITS, PLAN_PRICE_BAHT,
  REFERENCE_AGE_RANGE, REFERENCE_OBSERVATIONS, REFERENCE_SAMPLE, baht,
  // Explicit extension: `npm test` loads this file directly under node, whose ESM resolver will
  // not guess one. Same reason `lib/uploadSlot.ts` spells out `../scanQuality.ts`.
} from "./lib/productFacts.ts";

export type Locale = "th" | "en";
export type Market = "TH" | "GLOBAL";

/**
 * Every count in the public copy is interpolated from `lib/productFacts`, never typed in.
 *
 * This block used to hold "85+ facial measurements" and "80+ facial measurements" nine lines
 * apart, both wrong and each wrong in a different direction, and both invisible to every test in
 * the repository because a number inside a string is not connected to anything. Interpolating them
 * makes the marketing copy fail the build when the engine changes, which is the only way a page
 * that is read by customers before it is read by anyone else stays honest.
 */
export const siteCopy = {
  en: {
    nav: ["Product", "Research", "Safety", "Clinics", "Pricing"],
    start: "Start my analysis",
    sample: "See sample analysis",
    hero: "Your appearance is part of every first impression.",
    heroBody:
      "Understand it. Invest in yourself. Improve with intention. We analyze your face to show what matters most and build a personalized path beyond generic advice.",
    assurances: [
      "Secure processing",
      `${MEASURED_METRICS} measured ratios and angles`,
      "Your data stays private",
    ],
    analysisTitle: "You can’t improve what you can’t see.",
    analysisBody:
      `We measure ${MEASURED_METRICS} ratios and angles from your facial landmarks, covering ${CATALOG_MEASURED} of the ${CATALOG_TOTAL} characteristics in our catalogue. The other ${CATALOG_TOTAL - CATALOG_MEASURED} are listed as not measured, each with the reason a single photograph cannot answer it.`,
    interactive: "Interactive sample · Hover or tap a metric",
    experimental:
      `Every measurement is marked experimental in our own engine. ${REFERENCE_OBSERVATIONS} of them can be compared with a published cohort of ${REFERENCE_SAMPLE} Thai adults aged ${REFERENCE_AGE_RANGE}; the rest describe your face against itself.`,
    safetyTitle: "Built for informed decisions, not pressure.",
    safety: [
      [
        "Secure processing",
        "Your data stays private with clear user control and consent.",
      ],
      [
        "Transparent scoring",
        "See the factors, weighting and limits behind the result.",
      ],
      [
        "Preview limitations",
        "Possibilities, not promises, predictions or guarantees.",
      ],
      [
        "Shareable consultation report",
        "Bring your analysis, goals and questions into a professional consultation.",
      ],
    ],
    pricingTitle: "Start with clarity.\nKeep improving every month.",
    pricingBody:
      "Start free, then upgrade for the full set of measurements, a development plan and face simulations.",
    freeTitle: "Free",
    freeBody: "A partial read: your overall score and one pillar of the analysis.",
    freeFeatures: [
      "Overall score and one pillar of the analysis",
      "Prioritised questions to bring to a consultation",
      `${PLAN_LIMITS.free.chatTurns} chat questions a month`,
    ],
    // Said on the card rather than discovered after signing up. Free does not render a face at
    // all, and the analysis it does read is one pillar of four — both are what the tier is, not
    // something to find out after signing up.
    //
    // Written out rather than built from `PLAN_LIMITS.free.simulations`, which is now 0: the
    // template would have produced "0 simulations a month", which reads as an allowance that
    // happens to be empty this month rather than as a tier that does not include the feature.
    freeNote: "Your overall score and one pillar of the analysis. No face simulation and no development plan on this tier.",
    startFree: "Start free",
    completeTitle: "Plus",
    membership: "Monthly membership",
    completeBody:
      "Every measurement the engine produces, and a development plan built from your own numbers.",
    completeFeatures: [
      `All ${MEASURED_METRICS} measured metrics, nothing withheld`,
      "A development plan built from your own measurements",
      `${PLAN_LIMITS.plus.simulations} face simulations a month`,
      `${PLAN_LIMITS.plus.chatTurns} chat questions a month`,
    ],
    proNote: `Pro is ${baht(PLAN_PRICE_BAHT.pro)}/month for unlimited simulations and chat.`,
    // There is no card form yet — an Omise merchant account needs a registered company. Orders are
    // settled by bank transfer and activated by hand, which is what `PricingPanel` already does and
    // what a price with a buy button beside it has to admit before the click, not after it.
    paymentNote:
      "Paid plans are settled by bank transfer and activated once we confirm it. There is no card checkout yet.",
    startMonthly: "Choose Plus",
    cancel: "Cancel anytime.",
    forYou: "For you",
    userCtaTitle: "Build a plan for your face.",
    userCtaBody: "Understand. Preview. Decide.",
    forClinics: "For clinics",
    clinicCtaTitle: "Bring your measurements into the consultation.",
    clinicCtaBody: "We are looking for the first clinics to try this with.",
    joinPilot: "Talk to us about a pilot",
    footer: "Educational analysis only. Not medical advice.",
    about: {
      label: "About us",
      title: "Meet DOODEE",
      body: "DOODEE is an AI pre-consultation companion for facial assessment. It helps you understand your own proportions and arrive at a clinic with informed questions.",
      values: [
        [
          "Objective assessment",
          "Structure and proportion read from anatomical landmarks, with no sales pressure attached to the result.",
        ],
        [
          "Privacy by design",
          "Images live in a private bucket behind expiring signed links, and are processed only to build your report.",
        ],
        [
          "Your own features",
          "The analysis surfaces what is distinctive about your face and what is worth asking a clinician, not a single template to converge on.",
        ],
      ],
      bannerLabel: "Why check first?",
      bannerTitle: "Less hesitation, more value from every consultation",
      bannerBody:
        "A procedure decision made on a vague feeling becomes a decision made on measurements you can point at and question.",
    },
    data: {
      label: "Data we use",
      title: "Transparent about what is measured, and what is not",
      body: "DOODEE reads facial geometry to build a clear, non-judgmental report. Every limitation below is stated rather than hidden.",
      items: [
        [
          "2D landmark ratios",
          "Ratios measured within a single image from facial landmarks. No millimetre calibration, and no Golden Ratio beauty score.",
        ],
        [
          "Skin signals, compared within one photo",
          "Tone evenness, redness, under-eye shadow and shine, each measured as one part of your face against another part of the same photo — so the room's lighting cancels out instead of being reported as your skin. Where a photo is too dark, too uneven or too colour-cast to read, you get told that rather than a number.",
        ],
        [
          "Thai photographic reference",
          `Experimental comparison against mean and SD from ${REFERENCE_SAMPLE} Thai adults aged ${REFERENCE_AGE_RANGE}. Only ${REFERENCE_OBSERVATIONS} of the ${MEASURED_METRICS} measurements have a published figure to be scored against; the rest are your face compared with itself. A reference population, not a beauty standard.`,
        ],
        [
          "Private storage",
          "A private bucket with expiring signed links. Adult scans expire after 30 days; minors' after 24 hours.",
        ],
      ],
      guaranteeTitle: "What we commit to",
      guarantees: [
        "Your face images are never sold, and never shared for advertising or training.",
        "Images are processed only to generate your own report. They stay on our systems unless you turn on skin analysis, which sends the front photo to our AI provider to be read — off by default, and switchable off again in Settings.",
        "You can delete your scan history, or your whole account, at any time.",
      ],
    },
    contact: {
      label: "Contact us",
      title: "We are here to help",
      body: "Whether you use DOODEE yourself, run a clinic, or want to partner with us, the team reads every message.",
      channelsTitle: "Direct channels",
      lineLabel: "LINE Official Account",
      emailLabel: "Email support",
      partnerLabel: "Clinic partnership",
      hoursTitle: "Support hours",
      hours: "Mon–Fri 09:00–18:00 (ICT)",
      write: "Write to us",
    },
    login: {
      back: "Back to home",
      titleLead: "Sign in to",
      google: "Continue with Google",
      googleBusy: "Connecting...",
      preparing: "Preparing your experience",
      preparingBody: "Setting up your personal analysis",
      referralToggle: "Have a referral code?",
      referralLabel: "Referral code",
      referralPlaceholder: "Enter code",
      apply: "Apply",
      referralIdle: "Your code will be linked to this account.",
      referralTooShort: "Enter your referral code.",
      // Not "applied": nothing has been. The form only checks the code is long enough to exist —
      // there is no account to attach it to until Google has answered — and the redemption
      // happens after sign-in, where it can still be refused.
      referralSaved: "Code saved. It is claimed once you sign in.",
      referralRejected: "You are signed in, but the code %s could not be claimed. It may be mistyped, already used, or expired.",
      referralContinue: "Continue without it",
      legalLead: "By continuing, you agree to the",
      terms: "Terms",
      legalMid: "and acknowledge the",
      privacy: "Privacy Policy",
      signInFailed: "Could not sign in. Please try again.",
      tabSignIn: "Sign in",
      tabSignUp: "Create account",
      or: "or",
      email: "Email",
      emailPlaceholder: "you@example.com",
      password: "Password",
      passwordPlaceholder: "At least 8 characters",
      // Labels for the eye toggle beside the password field. It has no visible text, so
      // without these the only thing a screen reader announces is "button".
      showPassword: "Show password",
      hidePassword: "Hide password",
      submitSignIn: "Sign in",
      submitSignUp: "Create account",
      busy: "Please wait...",
      forgot: "Forgot your password?",
      resetSent: "If that email has an account, a reset link is on its way.",
      heroTitle: "AI-Powered Facial Harmony Analysis",
      heroSubtitle: "Understand your proportions with calibrated scientific precision and actionable aesthetic guidance.",
      feature1Title: "12 Calibrated Facial Ratios",
      feature1Desc: "Benchmarked against Thai and international adult aesthetic standards.",
      feature2Title: "Bank-Grade Privacy Protection",
      feature2Desc: "256-bit SSL encryption. Your photographs are never sold, and are shared only with our AI provider, only if you turn skin analysis on.",
      feature3Title: "Personalized Aesthetic Strategy",
      feature3Desc: "Explore tailored improvement plans and virtual 3D simulation.",
      trust1: "85+ Facial Keypoints",
      trust2: "PDPA & Privacy Compliant",
      trust3: "Instant 3D Calibration",
      pwdWeak: "Weak",
      pwdFair: "Fair",
      pwdGood: "Good",
      pwdStrong: "Strong",
      ruleLength: "At least 8 characters",
      ruleNumber: "Includes numbers",
      ruleLetter: "Includes letters",
      acceptTerms: "I agree to the Terms of Service and Privacy Policy",
      securityBadge: "256-bit SSL Secure & Encrypted Connection",
      errTerms: "Please accept the Terms of Service and Privacy Policy to continue.",
      displayName: "Full name",
      displayNamePlaceholder: "e.g. Alex Morgan",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Re-enter your password",
      passwordsMatch: "Passwords match",
      passwordsMismatch: "Passwords do not match",
      errName: "Please enter your name.",
      errPasswordMismatch: "Passwords do not match.",
      errEmail: "Enter a valid email address.",
      errShort: "Password must be at least 8 characters.",
      errEmailInUse: "That email already has an account. Sign in instead.",
      errInvalidEmail: "That email address is not valid.",
      errWeakPassword: "That password is too easy to guess. Try a longer one.",
      errBadCredentials: "Email or password is incorrect.",
      errDisabled: "This account has been suspended. Contact us.",
      errTooMany: "Too many attempts. Wait a moment and try again.",
      errNetwork: "Cannot reach the server. Check your connection.",
      errPopupClosed: "The Google window was closed before finishing.",
      errPopupBlocked: "Your browser blocked the sign-in window. Allow pop-ups for this site and try again.",
      errUnauthorizedDomain: "This domain is not authorised for sign-in. Please tell the site administrator.",
      errMethodDisabled: "Email sign-in is not switched on for this site yet.",
      errGeneric: "Something went wrong. Please try again.",
    },
    scan: {
      autoCapture: "Auto capture",
      voiceOn: "Spoken guidance on",
      voiceOff: "Spoken guidance off",
      progress: "%d of %d complete",
      exit: "Exit face scan",
      preview: "Live camera preview",
      // Named for what it is. "On-device processing" on a screen whose next act is to upload
      // three photographs to a server reads as a promise that nothing leaves the phone.
      onDevice: "Face tracking runs on your device",
      fpsLive: "%d FPS live",
      fpsTarget: "60 FPS target",
      loading: "Opening camera and loading face tracking…",
      cameraUnavailable: "Camera unavailable.",
      cameraDenied: "Camera access is required. Allow camera access in your browser, then try again.",
      uploadFailed: "Upload failed.",
      retry: "Try again",
      complete: "Capture complete.",
      // Not "three verified angles": nothing on this device verifies anything about them beyond
      // the pose and exposure gate that let the shutter fire. The measurement happens server-side
      // afterwards, and it is allowed to reject them. The Thai copy always said this correctly.
      completeBody: "All three angles are captured. Sending them for analysis…",
      // `holdLabel` ("Selecting the best frame") is gone with the element that carried it — see
      // the note in ScanPage where the three-dot strip used to be. These two say what the hold
      // actually is: frames are counted, not compared, and the current one is taken at the end.
      hintCapturing: "Hold still — the photo is taken for you",
      hintMoving: "Move naturally to any uncaptured angle",
      // The first line used to read "1.5–2 metres away", which is advice the app's own gate
      // refuses: `measurePose` rejects a face under 0.22 of the frame height as `too_far`, and a
      // face at two metres on a typical front camera is well under that. Following the printed
      // instruction produced "Move closer" — so the instruction now names the thing that is
      // actually measured.
      technical: ["Close enough to fill the guide", "High-resolution capture", "Hair away from face"],
      steps: {
        front: { label: "Front", short: "Face the camera" },
        left_profile: { label: "Left 90°", short: "Turn fully left" },
        right_profile: { label: "Right 90°", short: "Turn fully right" },
      },
      // Two registers over one set of codes. `live` speaks to someone standing in front of the
      // camera and can ask them to move; `still` speaks about a file that already exists and
      // cannot, so it says what is wrong with the photograph instead of what to do with a face.
      quality: {
        live: {
          good: "Good angle · Hold still",
          no_face: "Move your face into view",
          multiple_faces: "Only one face can be visible",
          too_dark: "Move into brighter light",
          too_bright: "Reduce glare or backlight",
          blurry: "Hold still — image is blurry",
          too_far: "Move closer",
          too_close: "Move farther away",
          off_centre: "Center your face",
          turn_farther_left: "Turn farther left",
          turn_farther_right: "Turn farther right",
          turn_slightly_left: "Turn slightly left",
          turn_slightly_right: "Turn slightly right",
          tilt_up: "Tilt up slightly",
          tilt_down: "Tilt down slightly",
          level_head: "Keep your head level",
          relax_expression: "Relax your expression",
          starting: "Camera ready · Starting face tracking…",
          finding_face: "Finding your face…",
          checking_angle: "Checking the angle…",
          hold_still: "Keep completely still",
          selecting_frame: "Angle is good — hold it for the shutter",
          position_for_step: "Move your face into the guide",
          face_too_small: "The face in this photo is too small to measure",
          sideways: "This photo is on its side",
          unsupported_heic: "This file format cannot be opened",
          unreadable_image: "This file could not be opened as an image",
          file_too_large: "This file is too large",
          uneven_lighting: "Even out the light — one side of your face is darker",
          colour_cast: "The light here is too strongly coloured",
          blown_highlights: "Too much direct light on your face",
        },
        still: {
          good: "This photo works",
          no_face: "No face found in this photo",
          multiple_faces: "More than one face in this photo — use one with only you in it",
          too_dark: "This photo is too dark to measure",
          too_bright: "Too much glare or backlight in this photo",
          blurry: "This photo is too blurry to measure",
          too_far: "The face in this photo is too small",
          too_close: "The face fills too much of this photo",
          off_centre: "The face is cut off at the edge of this photo",
          turn_farther_left: "The head is not turned far enough left in this photo",
          turn_farther_right: "The head is not turned far enough right in this photo",
          turn_slightly_left: "The head is turned too far right in this photo",
          turn_slightly_right: "The head is turned too far left in this photo",
          tilt_up: "The chin is too low in this photo",
          tilt_down: "The chin is too high in this photo",
          level_head: "The head is tilted sideways in this photo",
          relax_expression: "This photo is a smile",
          starting: "Preparing…",
          finding_face: "Looking for a face…",
          checking_angle: "Checking the angle…",
          hold_still: "Checking…",
          selecting_frame: "Checking…",
          position_for_step: "Choose a photo for this angle",
          face_too_small: "The face is too far away in this photo — use one taken closer",
          sideways: "This photo is on its side. Rotate it upright and try again.",
          unsupported_heic: "iPhone HEIC photos cannot be opened here. Set Camera → Formats to “Most Compatible”, or share the photo to yourself first — both give you a JPEG.",
          unreadable_image: "This file could not be opened as an image",
          file_too_large: "This file is larger than 10 MB",
          uneven_lighting: "One side of the face is much darker than the other in this photo",
          colour_cast: "The light in this photo is too strongly coloured to read skin through",
          blown_highlights: "Parts of the face are blown out in this photo",
        },
      },
      upload: {
        cta: "Upload a photo instead",
        forStep: "Upload a photo for %s",
        // Said up front, because the two profile slots want a near-full 90° turn and almost
        // nobody has that in their camera roll. Letting people discover it by having five old
        // selfies rejected in a row is the worst version of this feature.
        hint: "Take the photo with any camera app, or ask someone to take it — old selfies rarely have the side angles.",
        checking: "Checking this photo…",
        chooseAnother: "Choose a different photo",
        badge: "Uploaded",
        redo: "Replace",
        movedToStep: "This looks like %s — saved there instead.",
        smileWarning: "This photo is a smile. Mouth and cheek measurements will be slightly off; a neutral expression is more accurate.",
        useAnyway: "Use it anyway",
      },
      review: {
        title: "Check your photos",
        body: "One or more of these came from a file rather than the camera, so we need you to confirm before sending.",
        attestation: "These photos are of me, and I agree to have them analysed.",
        submit: "Send for analysis",
        submitBlocked: "Tick the box above to continue",
      },
    },
  },
  th: {
    nav: ["การวิเคราะห์", "งานวิจัย", "มาตรฐาน", "สำหรับคลินิก", "ราคา"],
    start: "เริ่มวิเคราะห์",
    sample: "ดูตัวอย่างผลวิเคราะห์",
    hero: "วิเคราะห์ใบหน้าอย่างเข้าใจ เพื่อการตัดสินใจที่เหมาะกับคุณ",
    heroBody:
      "เราใช้เทคโนโลยีวิเคราะห์โครงสร้างใบหน้าของคุณด้วยข้อมูลเชิงลึก เพื่อให้คุณเข้าใจจุดเด่นและสัดส่วนของใบหน้า พร้อมรับคำแนะนำที่ออกแบบให้เหมาะกับคุณ",
    assurances: [
      "ประมวลผลข้อมูลอย่างปลอดภัย",
      `วัดอัตราส่วนและมุมบนใบหน้า ${MEASURED_METRICS} ค่า`,
      "ข้อมูลปลอดภัย และเป็นส่วนตัว",
    ],
    analysisTitle: "เข้าใจความสมดุลและจุดเด่นบนใบหน้าคุณ",
    analysisBody:
      `เราวัดอัตราส่วนและมุมบนใบหน้า ${MEASURED_METRICS} ค่า ครอบคลุม ${CATALOG_MEASURED} จาก ${CATALOG_TOTAL} หัวข้อในรายการของเรา อีก ${CATALOG_TOTAL - CATALOG_MEASURED} หัวข้อระบุไว้ว่ายังวัดไม่ได้ พร้อมเหตุผลว่าทำไมภาพถ่ายภาพเดียวจึงตอบไม่ได้`,
    interactive: "ตัวอย่างผลวิเคราะห์ · แตะเพื่อดูรายละเอียด",
    experimental:
      `ค่าที่วัดได้ทุกค่าถูกกำกับว่าเป็นค่าเชิงทดลองในระบบของเราเอง มี ${REFERENCE_OBSERVATIONS} ค่าที่เทียบกับกลุ่มอ้างอิงคนไทย ${REFERENCE_SAMPLE} คน อายุ ${REFERENCE_AGE_RANGE} ปีได้ ส่วนที่เหลือเป็นการเทียบใบหน้าคุณกับตัวเอง`,
    safetyTitle: "ข้อมูลที่ชัดขึ้น เพื่อการตัดสินใจที่เป็นของคุณ",
    safety: [
      [
        "ประมวลผลข้อมูลอย่างปลอดภัย",
        "ข้อมูลของคุณเป็นส่วนตัว พร้อมสิทธิ์ในการควบคุมและการยินยอมที่ชัดเจน",
      ],
      [
        "เข้าใจที่มาของคะแนน",
        "ดูปัจจัย น้ำหนัก และข้อจำกัดที่มีผลต่อผลลัพธ์",
      ],
      [
        "ข้อจำกัดของภาพจำลอง",
        "ภาพจำลองแสดงแนวทางที่เป็นไปได้ ไม่ใช่การคาดการณ์หรือการรับประกันผลลัพธ์",
      ],
      [
        "เตรียมตัวก่อนปรึกษาผู้เชี่ยวชาญ",
        "สรุปผลวิเคราะห์ เป้าหมาย และคำถามสำคัญไว้สำหรับการพูดคุย",
      ],
    ],
    pricingTitle: "เห็นภาพชัดขึ้นในวันนี้\nและติดตามความเปลี่ยนแปลงต่อไป",
    pricingBody:
      "เริ่มใช้ฟรี แล้วเลือกอัปเกรดเมื่อต้องการค่าที่วัดได้ครบทุกค่า แผนพัฒนาตนเอง และการจำลองใบหน้า",
    freeTitle: "ฟรี",
    freeBody: "เห็นบางส่วน: คะแนนภาพรวมและผลวิเคราะห์ 1 มิติ",
    freeFeatures: [
      "คะแนนภาพรวมและผลวิเคราะห์ 1 มิติ",
      "คำถามสำคัญสำหรับไปปรึกษาแพทย์",
      `ถามแชทได้ ${PLAN_LIMITS.free.chatTurns} ข้อความต่อเดือน`,
    ],
    freeNote: "เห็นคะแนนภาพรวมและผลวิเคราะห์ 1 มิติ · ไม่มีการจำลองใบหน้า และไม่มีแผนพัฒนาตนเอง",
    startFree: "เริ่มวิเคราะห์ฟรี",
    completeTitle: "พลัส",
    membership: "สมาชิกแบบรายเดือน",
    completeBody:
      "ได้ค่าที่วัดได้ครบทุกค่า พร้อมแผนพัฒนาตนเองที่สร้างจากตัวเลขของคุณเอง",
    completeFeatures: [
      `ค่าที่วัดได้ครบทั้ง ${MEASURED_METRICS} ค่า ไม่มีการซ่อน`,
      "แผนพัฒนาตนเองที่สร้างจากค่าที่วัดได้ของคุณ",
      `จำลองใบหน้าได้ ${PLAN_LIMITS.plus.simulations} ครั้งต่อเดือน`,
      `ถามแชทได้ ${PLAN_LIMITS.plus.chatTurns} ข้อความต่อเดือน`,
    ],
    proNote: `แผนโปร ${baht(PLAN_PRICE_BAHT.pro)}/เดือน จำลองใบหน้าและแชทได้ไม่จำกัด`,
    paymentNote:
      "แผนแบบเสียเงินชำระด้วยการโอนเงิน และเปิดสิทธิ์หลังทีมงานยืนยันการชำระเงิน ยังไม่มีการตัดบัตรอัตโนมัติ",
    startMonthly: "เลือกแผนพลัส",
    cancel: "ยกเลิกได้ทุกเมื่อ",
    forYou: "สำหรับคุณ",
    userCtaTitle: "รู้ว่าควรเริ่มตรงไหนบนใบหน้าคุณ",
    userCtaBody: "วิเคราะห์ เห็นภาพ และวางลำดับอย่างชัดเจน",
    forClinics: "สำหรับคลินิก",
    clinicCtaTitle: "นำค่าที่วัดได้เข้าไปใช้ในห้องปรึกษา",
    clinicCtaBody: "เรากำลังมองหาคลินิกกลุ่มแรกที่จะทดลองใช้ด้วยกัน",
    joinPilot: "คุยกับเราเรื่องการทดลองใช้",
    footer:
      "ผลวิเคราะห์ใช้เพื่อประกอบการตัดสินใจ ไม่ใช่คำวินิจฉัยหรือคำแนะนำทางการแพทย์",
    about: {
      label: "เกี่ยวกับเรา",
      title: "ทำความรู้จักกับ DOODEE",
      body: "DOODEE คือผู้ช่วยประเมินใบหน้าด้วย AI ก่อนเข้าพบแพทย์ เพื่อให้คุณเข้าใจสัดส่วนใบหน้าของตัวเอง และเตรียมคำถามสำคัญไปคุยกับคลินิกได้อย่างมั่นใจ",
      values: [
        [
          "ประเมินอย่างเป็นกลาง",
          "อ่านโครงหน้าและสัดส่วนจากจุดอ้างอิงทางกายวิภาค ผลลัพธ์ไม่ผูกกับการเชียร์ขายคอร์ส",
        ],
        [
          "ออกแบบโดยยึดความเป็นส่วนตัว",
          "ภาพเก็บใน bucket ส่วนตัวและเปิดผ่านลิงก์ชั่วคราว ประมวลผลเพื่อสร้างรายงานของคุณเท่านั้น",
        ],
        [
          "เคารพลักษณะเฉพาะของคุณ",
          "ผลวิเคราะห์ชี้ให้เห็นสิ่งที่เป็นเอกลักษณ์บนใบหน้าคุณและประเด็นที่ควรถามแพทย์ ไม่ใช่แม่แบบเดียวที่ทุกคนต้องเดินเข้าหา",
        ],
      ],
      bannerLabel: "ทำไมต้องเช็กก่อน?",
      bannerTitle: "ลดความลังเล เพิ่มความคุ้มค่าให้ทุกการปรึกษา",
      bannerBody:
        "เปลี่ยนการตัดสินใจที่อิงความรู้สึกไม่แน่นอน ให้เป็นการตัดสินใจบนตัวเลขที่ชี้ได้และตั้งคำถามต่อได้",
    },
    data: {
      label: "ข้อมูลที่เราใช้",
      title: "โปร่งใสว่าวัดอะไร และไม่ได้วัดอะไร",
      body: "DOODEE อ่านเรขาคณิตใบหน้าเพื่อสร้างรายงานที่ชัดเจนและไม่ตัดสิน ข้อจำกัดทุกข้อด้านล่างระบุไว้ตรงๆ ไม่ได้ซ่อน",
      items: [
        [
          "สัดส่วนจาก landmark ภาพ 2D",
          "วัดอัตราส่วนภายในภาพเดียวกันจากจุด landmark บนใบหน้า ไม่แปลงเป็นมิลลิเมตร และไม่ใช้ Golden Ratio เป็นคะแนนความงาม",
        ],
        [
          "สัญญาณผิว วัดแบบเทียบภายในภาพเดียวกัน",
          "ความสม่ำเสมอของโทนสี รอยแดง ความคล้ำใต้ตา และความมัน วัดโดยเทียบส่วนหนึ่งของใบหน้ากับอีกส่วนในภาพเดียวกัน แสงในห้องจึงหักล้างกันเอง ไม่ถูกรายงานว่าเป็นผิวของคุณ ถ้าภาพมืดเกินไป แสงไม่สม่ำเสมอ หรือสีเพี้ยนจนอ่านไม่ได้ เราจะบอกตรงๆ แทนที่จะให้ตัวเลข",
        ],
        [
          "ค่าอ้างอิงจากภาพถ่ายคนไทย",
          `เปรียบเทียบเชิงทดลองกับค่าเฉลี่ยและส่วนเบี่ยงเบนจากคนไทย ${REFERENCE_SAMPLE} คน อายุ ${REFERENCE_AGE_RANGE} ปี มีเพียง ${REFERENCE_OBSERVATIONS} ค่าจาก ${MEASURED_METRICS} ค่าที่มีตัวเลขตีพิมพ์ให้เทียบได้ ที่เหลือเป็นการเทียบใบหน้าคุณกับตัวเอง เป็นประชากรอ้างอิง ไม่ใช่เกณฑ์ความสวย`,
        ],
        [
          "พื้นที่จัดเก็บส่วนตัว",
          "เก็บใน bucket ส่วนตัวและเปิดด้วยลิงก์ชั่วคราว ภาพผู้ใหญ่หมดอายุใน 30 วัน ผู้เยาว์ 24 ชั่วโมง",
        ],
      ],
      guaranteeTitle: "สิ่งที่เรายึดถือ",
      guarantees: [
        "ไม่ขายภาพใบหน้าของคุณ และไม่ส่งต่อเพื่อการโฆษณาหรือใช้ฝึกโมเดล",
        "ประมวลผลภาพเพื่อสร้างรายงานของคุณเท่านั้น ภาพอยู่ในระบบของเรา ยกเว้นกรณีที่คุณเปิดใช้การวิเคราะห์ผิว ซึ่งจะส่งภาพหน้าตรงให้ผู้ให้บริการ AI อ่าน — ปิดอยู่โดยค่าเริ่มต้น และปิดกลับได้ในหน้าตั้งค่า",
        "ลบประวัติการสแกน หรือลบบัญชีทั้งหมด ได้ทุกเมื่อ",
      ],
    },
    contact: {
      label: "ติดต่อเรา",
      title: "พร้อมพูดคุยและตอบทุกคำถาม",
      body: "ไม่ว่าคุณจะเป็นผู้ใช้งาน คลินิกความงาม หรือสนใจร่วมเป็นพันธมิตร ทีมงาน DOODEE อ่านทุกข้อความ",
      channelsTitle: "ช่องทางติดต่อ",
      lineLabel: "LINE Official Account",
      emailLabel: "อีเมลฝ่ายสนับสนุน",
      partnerLabel: "ร่วมเป็นคลินิกพันธมิตร",
      hoursTitle: "เวลาทำการ",
      hours: "จันทร์–ศุกร์ 09:00–18:00 น. (เว้นวันหยุดนักขัตฤกษ์)",
      write: "ส่งข้อความถึงเรา",
    },
    login: {
      back: "กลับหน้าแรก",
      titleLead: "เข้าสู่ระบบ",
      google: "ดำเนินการต่อด้วย Google",
      googleBusy: "กำลังเชื่อมต่อ...",
      preparing: "กำลังเตรียมพร้อม",
      preparingBody: "กำลังตั้งค่าการวิเคราะห์ของคุณ",
      referralToggle: "มีโค้ดแนะนำเพื่อนไหม?",
      referralLabel: "โค้ดแนะนำเพื่อน",
      referralPlaceholder: "กรอกโค้ด",
      apply: "ใช้โค้ด",
      referralIdle: "โค้ดจะถูกผูกกับบัญชีนี้",
      referralTooShort: "กรอกโค้ดแนะนำเพื่อนของคุณ",
      referralSaved: "เก็บโค้ดไว้แล้ว จะใช้ให้ตอนเข้าสู่ระบบ",
      referralRejected: "เข้าสู่ระบบแล้ว แต่ใช้โค้ด %s ไม่ได้ อาจพิมพ์ผิด ถูกใช้ไปแล้ว หรือหมดอายุ",
      referralContinue: "ไปต่อโดยไม่ใช้โค้ด",
      legalLead: "การดำเนินการต่อถือว่าคุณยอมรับ",
      terms: "ข้อกำหนดการใช้งาน",
      legalMid: "และรับทราบ",
      privacy: "นโยบายความเป็นส่วนตัว",
      signInFailed: "เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
      tabSignIn: "เข้าสู่ระบบ",
      tabSignUp: "สมัครสมาชิก",
      or: "หรือ",
      email: "อีเมล",
      emailPlaceholder: "you@example.com",
      password: "รหัสผ่าน",
      passwordPlaceholder: "อย่างน้อย 8 ตัวอักษร",
      showPassword: "แสดงรหัสผ่าน",
      hidePassword: "ซ่อนรหัสผ่าน",
      submitSignIn: "เข้าสู่ระบบ",
      submitSignUp: "สมัครสมาชิก",
      busy: "กรุณารอสักครู่...",
      forgot: "ลืมรหัสผ่าน?",
      resetSent: "ถ้าอีเมลนี้มีบัญชีอยู่ ลิงก์ตั้งรหัสผ่านใหม่กำลังส่งไป",
      heroTitle: "ยกระดับสัดส่วนใบหน้า ด้วยการวิเคราะห์ทางวิทยาศาสตร์ AI",
      heroSubtitle: "เข้าใจสัดส่วนใบหน้าของคุณอย่างแม่นยำตามหลักวิทยาศาสตร์ พร้อมคำแนะนำพัฒนาที่ตรงจุด",
      feature1Title: "สัดส่วน 12 มิติที่แม่นยำ",
      feature1Desc: "คำนวณเปรียบเทียบกับกลุ่มอ้างอิงมาตรฐานคนไทยและสากล",
      feature2Title: "ความปลอดภัยระดับมาตรฐานสากล",
      feature2Desc: "เข้ารหัสปลอดภัย 256-bit ไม่ขายรูปถ่ายของคุณ และส่งให้ผู้ให้บริการ AI เฉพาะเมื่อคุณเปิดใช้การวิเคราะห์ผิวเท่านั้น",
      feature3Title: "วางแผนพัฒนาสัดส่วนเฉพาะบุคคล",
      feature3Desc: "ค้นพบแนวทางพัฒนาทั้งหัตถการและการปรับลุคอย่างเป็นธรรมชาติ",
      trust1: "วิเคราะห์กว่า 85 จุด",
      trust2: "มาตรฐานความปลอดภัย PDPA",
      trust3: "ประมวลผลแม่นยำทันที",
      pwdWeak: "ง่ายเกินไป",
      pwdFair: "ปานกลาง",
      pwdGood: "ปลอดภัย",
      pwdStrong: "ปลอดภัยมาก",
      ruleLength: "อย่างน้อย 8 ตัวอักษร",
      ruleNumber: "มีตัวเลขผสม",
      ruleLetter: "มีตัวอักษรผสม",
      acceptTerms: "ฉันยอมรับข้อกำหนดการใช้งานและนโยบายความเป็นส่วนตัว",
      securityBadge: "เชื่อมต่อปลอดภัยด้วยการเข้ารหัส 256-bit SSL",
      errTerms: "กรุณายอมรับข้อกำหนดการใช้งานและนโยบายความเป็นส่วนตัวก่อนดำเนินการต่อ",
      displayName: "ชื่อผู้ใช้ หรือ ชื่อ-นามสกุล",
      displayNamePlaceholder: "เช่น สมชาย ประเสริฐ",
      confirmPassword: "ยืนยันรหัสผ่าน",
      confirmPasswordPlaceholder: "กรอกรหัสผ่านอีกครั้ง",
      passwordsMatch: "รหัสผ่านตรงกัน",
      passwordsMismatch: "รหัสผ่านไม่ตรงกัน",
      errName: "กรุณากรอกชื่อผู้ใช้หรือชื่อ-นามสกุลของคุณ",
      errPasswordMismatch: "รหัสผ่านและยืนยันรหัสผ่านไม่ตรงกัน",
      errEmail: "กรอกอีเมลให้ถูกต้อง",
      errShort: "รหัสผ่านต้องยาวอย่างน้อย 8 ตัวอักษร",
      errEmailInUse: "อีเมลนี้มีบัญชีอยู่แล้ว กรุณาเข้าสู่ระบบแทน",
      errInvalidEmail: "รูปแบบอีเมลไม่ถูกต้อง",
      errWeakPassword: "รหัสผ่านเดาง่ายเกินไป ลองตั้งให้ยาวขึ้น",
      errBadCredentials: "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
      errDisabled: "บัญชีนี้ถูกระงับ กรุณาติดต่อทีมงาน",
      errTooMany: "ลองผิดหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
      errNetwork: "เชื่อมต่อเซิร์ฟเวอร์ไม่ได้ ตรวจสอบอินเทอร์เน็ตของคุณ",
      errPopupClosed: "หน้าต่าง Google ถูกปิดก่อนเสร็จ",
      errPopupBlocked: "เบราว์เซอร์บล็อกหน้าต่างเข้าสู่ระบบ กรุณาอนุญาตป๊อปอัปสำหรับเว็บนี้ แล้วลองใหม่",
      errUnauthorizedDomain: "โดเมนนี้ยังไม่ได้รับอนุญาตให้เข้าสู่ระบบ กรุณาแจ้งผู้ดูแลระบบ",
      errMethodDisabled: "ยังไม่ได้เปิดการสมัครด้วยอีเมลสำหรับเว็บนี้",
      errGeneric: "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
    },
    scan: {
      autoCapture: "ถ่ายอัตโนมัติ",
      voiceOn: "เสียงบอกท่าเปิดอยู่",
      voiceOff: "เสียงบอกท่าปิดอยู่",
      progress: "ถ่ายแล้ว %d จาก %d มุม",
      exit: "ออกจากการสแกน",
      preview: "ภาพสดจากกล้อง",
      onDevice: "ระบบตรวจจับใบหน้าทำงานบนเครื่องคุณ",
      fpsLive: "%d FPS",
      fpsTarget: "เป้าหมาย 60 FPS",
      loading: "กำลังเปิดกล้องและโหลดระบบตรวจจับใบหน้า…",
      cameraUnavailable: "ใช้กล้องไม่ได้",
      cameraDenied: "ต้องอนุญาตให้ใช้กล้องก่อน เปิดสิทธิ์กล้องในเบราว์เซอร์แล้วลองใหม่ หรืออัปโหลดรูปแทนได้",
      uploadFailed: "ส่งรูปไม่สำเร็จ",
      retry: "ลองอีกครั้ง",
      complete: "ถ่ายครบแล้ว",
      completeBody: "ได้ครบสามมุมแล้ว กำลังส่งไปวิเคราะห์…",
      hintCapturing: "อยู่นิ่ง ๆ ระบบจะถ่ายให้เอง",
      hintMoving: "ขยับหน้าไปมุมไหนก็ได้ที่ยังไม่ได้ถ่าย",
      technical: ["เข้าใกล้พอให้ใบหน้าเต็มกรอบ", "ถ่ายความละเอียดสูง", "เก็บผมให้พ้นใบหน้า"],
      steps: {
        front: { label: "หน้าตรง", short: "หันหน้าเข้ากล้อง" },
        left_profile: { label: "ซ้าย 90°", short: "หันซ้ายจนสุด" },
        right_profile: { label: "ขวา 90°", short: "หันขวาจนสุด" },
      },
      quality: {
        live: {
          good: "มุมใช้ได้ · นิ่งไว้",
          no_face: "ขยับใบหน้าเข้ามาในกรอบ",
          multiple_faces: "ให้มีใบหน้าเดียวในกรอบ",
          too_dark: "ย้ายไปที่ที่สว่างกว่านี้",
          too_bright: "ลดแสงจ้าหรือแสงย้อน",
          blurry: "ถือนิ่งๆ ภาพยังเบลอ",
          too_far: "ขยับเข้ามาใกล้อีกนิด",
          too_close: "ถอยออกไปอีกนิด",
          off_centre: "จัดใบหน้าให้อยู่กลางกรอบ",
          turn_farther_left: "หันซ้ายอีกหน่อย",
          turn_farther_right: "หันขวาอีกหน่อย",
          turn_slightly_left: "หันซ้ายนิดเดียว",
          turn_slightly_right: "หันขวานิดเดียว",
          tilt_up: "เงยขึ้นเล็กน้อย",
          tilt_down: "ก้มลงเล็กน้อย",
          level_head: "ตั้งศีรษะให้ตรง อย่าเอียง",
          relax_expression: "ทำหน้าปกติ ไม่ต้องยิ้ม",
          starting: "กล้องพร้อมแล้ว · กำลังเริ่มตรวจจับใบหน้า…",
          finding_face: "กำลังหาใบหน้า…",
          checking_angle: "กำลังตรวจมุม…",
          hold_still: "อยู่นิ่งๆ สักครู่",
          selecting_frame: "มุมใช้ได้ · นิ่งไว้ กำลังจะถ่าย",
          position_for_step: "จัดใบหน้าให้อยู่ในกรอบ",
          face_too_small: "ใบหน้าในรูปนี้เล็กเกินกว่าจะวัดได้",
          sideways: "รูปนี้ตะแคง",
          unsupported_heic: "เปิดไฟล์ชนิดนี้ไม่ได้",
          unreadable_image: "เปิดไฟล์นี้เป็นรูปภาพไม่ได้",
          file_too_large: "ไฟล์นี้ใหญ่เกินไป",
          uneven_lighting: "แสงเข้าข้างเดียว หันหน้าให้แสงถึงทั้งสองข้าง",
          colour_cast: "แสงตรงนี้มีสีเข้มเกินไป",
          blown_highlights: "แสงจ้าเกินไปบนใบหน้า",
        },
        still: {
          good: "รูปนี้ใช้ได้",
          no_face: "ไม่พบใบหน้าในรูปนี้",
          multiple_faces: "รูปนี้มีมากกว่าหนึ่งใบหน้า ใช้รูปที่มีคุณคนเดียว",
          too_dark: "รูปนี้มืดเกินกว่าจะวัดได้",
          too_bright: "รูปนี้มีแสงจ้าหรือแสงย้อนมากเกินไป",
          blurry: "รูปนี้เบลอเกินกว่าจะวัดได้",
          too_far: "ใบหน้าในรูปนี้เล็กเกินไป",
          too_close: "ใบหน้าเต็มเฟรมเกินไปในรูปนี้",
          off_centre: "ใบหน้าในรูปนี้ถูกตัดที่ขอบภาพ",
          turn_farther_left: "ในรูปนี้หันซ้ายไม่พอ",
          turn_farther_right: "ในรูปนี้หันขวาไม่พอ",
          turn_slightly_left: "ในรูปนี้หันไปทางขวามากเกินไป",
          turn_slightly_right: "ในรูปนี้หันไปทางซ้ายมากเกินไป",
          tilt_up: "ในรูปนี้ก้มหน้ามากเกินไป",
          tilt_down: "ในรูปนี้เงยหน้ามากเกินไป",
          level_head: "ในรูปนี้ศีรษะเอียงไปด้านข้าง",
          relax_expression: "รูปนี้เป็นรูปยิ้ม",
          starting: "กำลังเตรียม…",
          finding_face: "กำลังหาใบหน้า…",
          checking_angle: "กำลังตรวจมุม…",
          hold_still: "กำลังตรวจ…",
          selecting_frame: "กำลังตรวจ…",
          position_for_step: "เลือกรูปสำหรับมุมนี้",
          face_too_small: "ใบหน้าในรูปนี้อยู่ไกลเกินไป ใช้รูปที่ถ่ายใกล้กว่านี้",
          sideways: "รูปนี้ตะแคง หมุนรูปให้ตั้งตรงก่อนแล้วลองใหม่",
          unsupported_heic: "เปิดไฟล์ HEIC ของ iPhone ที่นี่ไม่ได้ ตั้งค่า กล้อง → รูปแบบ เป็น “ที่เข้ากันได้มากที่สุด” หรือแชร์รูปให้ตัวเองก่อน ทั้งสองวิธีจะได้ไฟล์ JPEG",
          unreadable_image: "เปิดไฟล์นี้เป็นรูปภาพไม่ได้",
          file_too_large: "ไฟล์นี้ใหญ่เกิน 10 MB",
          uneven_lighting: "รูปนี้แสงเข้าข้างเดียว หน้าข้างหนึ่งมืดกว่าอีกข้างมาก",
          colour_cast: "แสงในรูปนี้มีสีเข้มเกินกว่าจะอ่านค่าผิวได้",
          blown_highlights: "บางส่วนของใบหน้าในรูปนี้สว่างจนรายละเอียดหายไป",
        },
      },
      upload: {
        cta: "อัปโหลดรูปแทน",
        forStep: "อัปโหลดรูปสำหรับมุม%s",
        hint: "ถ่ายด้วยแอปกล้องอะไรก็ได้ หรือให้คนอื่นช่วยถ่าย · รูปเซลฟี่เก่ามักไม่มีมุมด้านข้าง",
        checking: "กำลังตรวจรูปนี้…",
        chooseAnother: "เลือกรูปอื่น",
        badge: "อัปโหลด",
        redo: "เปลี่ยนรูป",
        movedToStep: "รูปนี้เป็นมุม%s บันทึกไว้ช่องนั้นให้แล้ว",
        smileWarning: "รูปนี้เป็นรูปยิ้ม ค่าที่วัดบริเวณปากและแก้มจะคลาดเคลื่อนเล็กน้อย รูปหน้าปกติจะแม่นกว่า",
        useAnyway: "ใช้รูปนี้ต่อ",
      },
      review: {
        title: "ตรวจรูปก่อนส่ง",
        body: "มีรูปที่มาจากไฟล์ ไม่ได้มาจากกล้อง จึงต้องให้คุณยืนยันก่อนส่ง",
        attestation: "รูปเหล่านี้เป็นใบหน้าของฉัน และฉันยินยอมให้นำไปวิเคราะห์",
        submit: "ส่งไปวิเคราะห์",
        submitBlocked: "ติ๊กช่องด้านบนก่อนจึงจะส่งได้",
      },
    },
  },
} as const;
