# Generated by Django 5.2.16 on 2026-08-03 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('analysis', 'Analysis'), ('storage', 'Storage and history'), ('simulation', 'External AI simulation')], max_length=16)),
                ('policy_version', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deletion_pending', 'Deletion pending')], db_index=True, default='queued', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('age_band', models.CharField(choices=[('adult', '18 or older'), ('minor', 'Under 18')], max_length=8)),
                ('image_objects', models.JSONField(default=dict)),
                ('analysis_data', models.JSONField(blank=True, null=True)),
                ('formula_version', models.CharField(default='2026.1', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deletion_pending', 'Deletion pending')], db_index=True, default='queued', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('region', models.CharField(max_length=16)),
                ('parameters', models.JSONField(default=dict)),
                ('model_version', models.CharField(max_length=80)),
                ('before_object', models.CharField(blank=True, max_length=500)),
                ('after_object', models.CharField(blank=True, max_length=500)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='doodee.scan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
