# Generated by Django 5.2.16 on 2026-08-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0006_promo_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='selections',
            field=models.JSONField(default=list),
        ),
    ]
