# Generated by Django 5.2.17 on 2026-08-16 23:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0009_chatconversation_chatmessage_chatusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('discount_type', models.CharField(choices=[('percent', 'Percent off'), ('fixed', 'Fixed satang off')], default='percent', max_length=8)),
                ('discount_value', models.PositiveIntegerField()),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('once_per_user', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('min_amount_satang', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_th', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('description_th', models.CharField(blank=True, max_length=300)),
                ('description_en', models.CharField(blank=True, max_length=300)),
                ('price_satang', models.PositiveIntegerField(default=0)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('once', 'One-off')], default='month', max_length=8)),
                ('features', models.JSONField(blank=True, default=list)),
                ('grants_group', models.CharField(blank=True, max_length=64)),
                ('self_serve', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'price_satang'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_satang', models.PositiveIntegerField()),
                ('discount_satang', models.PositiveIntegerField(default=0)),
                ('total_satang', models.PositiveIntegerField()),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('provider', models.CharField(choices=[('manual', 'Manual / bank transfer'), ('omise', 'Omise')], default='manual', max_length=10)),
                ('provider_charge_id', models.CharField(blank=True, max_length=128)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='doodee.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='doodee.plan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_plans',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='doodee.plan'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='doodee.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='doodee.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-current_period_end',),
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='doodee.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='doodee.order')),
            ],
            options={
                'ordering': ('-redeemed_at',),
                'indexes': [models.Index(fields=['user', 'coupon'], name='doodee_coup_user_id_1f0c5e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='doodee_orde_user_id_63a8f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_charge_id__gt', '')), fields=('provider', 'provider_charge_id'), name='unique_provider_charge'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'current_period_end'], name='doodee_subs_user_id_95e554_idx'),
        ),
    ]
