# Generated by Django 5.2.17 on 2026-08-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0011_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
