# Generated by Django 5.2.17 on 2026-08-17 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0012_scan_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_active', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['date'], name='doodee_dail_date_adc136_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_active')],
            },
        ),
    ]
