# Generated by Django 5.2.17 on 2026-08-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0013_chatmessage_cache_write_tokens_dailyactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentevent',
            name='purpose',
            field=models.CharField(choices=[('analysis', 'Analysis'), ('storage', 'Storage and history'), ('simulation', 'Local facial simulation'), ('chat', 'Chat with a third-party model')], max_length=16),
        ),
    ]
