# Generated by Django 5.2.17 on 2026-08-17 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0014_alter_consentevent_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ('-updated_at',), 'verbose_name': 'ห้องแชท', 'verbose_name_plural': 'ห้องแชท'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'ข้อความแชท', 'verbose_name_plural': 'ข้อความแชท'},
        ),
        migrations.AlterModelOptions(
            name='chatusage',
            options={'verbose_name': 'โควตาแชท', 'verbose_name_plural': 'โควตาแชท'},
        ),
        migrations.AlterModelOptions(
            name='consentevent',
            options={'verbose_name': 'การให้ความยินยอม', 'verbose_name_plural': 'การให้ความยินยอม'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-created_at',), 'verbose_name': 'คูปองส่วนลด', 'verbose_name_plural': 'คูปองส่วนลด'},
        ),
        migrations.AlterModelOptions(
            name='couponredemption',
            options={'ordering': ('-redeemed_at',), 'verbose_name': 'การใช้คูปอง', 'verbose_name_plural': 'การใช้คูปอง'},
        ),
        migrations.AlterModelOptions(
            name='dailyactive',
            options={'ordering': ('-date',), 'verbose_name': 'ผู้ใช้งานรายวัน', 'verbose_name_plural': 'ผู้ใช้งานรายวัน'},
        ),
        migrations.AlterModelOptions(
            name='firebaseidentity',
            options={'verbose_name': 'บัญชี Firebase', 'verbose_name_plural': 'บัญชี Firebase'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'คำสั่งซื้อ', 'verbose_name_plural': 'คำสั่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('sort_order', 'price_satang'), 'verbose_name': 'แผน', 'verbose_name_plural': 'แผน'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('-created_at',), 'verbose_name': 'โค้ดรับสิทธิ์', 'verbose_name_plural': 'โค้ดรับสิทธิ์'},
        ),
        migrations.AlterModelOptions(
            name='promoredemption',
            options={'ordering': ('-redeemed_at',), 'verbose_name': 'การใช้โค้ดรับสิทธิ์', 'verbose_name_plural': 'การใช้โค้ดรับสิทธิ์'},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ('-created_at',), 'verbose_name': 'การสแกน', 'verbose_name_plural': 'การสแกน'},
        ),
        migrations.AlterModelOptions(
            name='simulation',
            options={'ordering': ('-created_at',), 'verbose_name': 'การจำลองผล', 'verbose_name_plural': 'การจำลองผล'},
        ),
        migrations.AlterModelOptions(
            name='simulationpreviewusage',
            options={'verbose_name': 'โควตาพรีวิวการจำลอง', 'verbose_name_plural': 'โควตาพรีวิวการจำลอง'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-current_period_end',), 'verbose_name': 'สมาชิกรายเดือน', 'verbose_name_plural': 'สมาชิกรายเดือน'},
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เริ่มเมื่อ'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='ตัวเลขจากการสแกนนี้คือสิ่งที่ส่งให้โมเดล ถ้าว่างแปลว่าการสแกนถูกลบไปแล้ว', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to='doodee.scan', verbose_name='การสแกนที่อ้างถึง'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='ชื่อห้อง'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='ตอบล่าสุด'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='โทเค็นที่เขียนลงแคช'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='ยิ่งมากยิ่งประหยัด ถ้าเป็น 0 ตั้งแต่ข้อความที่สองแปลว่าแคชไม่ทำงาน', verbose_name='โทเค็นที่อ่านจากแคช'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='ข้อความ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='doodee.chatconversation', verbose_name='ห้องแชท'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เมื่อ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='โทเค็นขาเข้า'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='โทเค็นขาออก'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'ผู้ใช้'), ('assistant', 'DOODEE')], max_length=9, verbose_name='ผู้พูด'),
        ),
        migrations.AlterField(
            model_name='chatusage',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='นับเฉพาะคำถามที่พิมพ์เอง คำถามสำเร็จรูปไม่กินโควตาเพราะไม่ได้เรียกโมเดล', verbose_name='ใช้ไปแล้ว (ครั้ง)'),
        ),
        migrations.AlterField(
            model_name='chatusage',
            name='period',
            field=models.DateField(help_text='วันที่ 1 ของเดือนที่นับโควตานี้', verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='chatusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usage', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='consentevent',
            name='accepted',
            field=models.BooleanField(default=True, verbose_name='ยินยอม'),
        ),
        migrations.AlterField(
            model_name='consentevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เมื่อ'),
        ),
        migrations.AlterField(
            model_name='consentevent',
            name='policy_version',
            field=models.CharField(help_text='เวอร์ชันของข้อความที่ผู้ใช้เห็นตอนกดยินยอม ใช้พิสูจน์ว่าเขาตกลงกับข้อความชุดไหน', max_length=32, verbose_name='เวอร์ชันนโยบาย'),
        ),
        migrations.AlterField(
            model_name='consentevent',
            name='purpose',
            field=models.CharField(choices=[('analysis', 'วิเคราะห์ใบหน้า'), ('storage', 'เก็บภาพและประวัติ'), ('simulation', 'จำลองผลในเครื่อง'), ('chat', 'ส่งตัวเลขให้โมเดลภายนอก (แชท)')], max_length=16, verbose_name='ยินยอมเรื่องอะไร'),
        ),
        migrations.AlterField(
            model_name='consentevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applies_to_plans',
            field=models.ManyToManyField(blank=True, help_text='ไม่เลือกอะไรเลย = ใช้ได้กับทุกแผน', related_name='coupons', to='doodee.plan', verbose_name='ใช้ได้กับแผน'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='อย่างน้อย 4 ตัวอักษร ลูกค้าพิมพ์โค้ดนี้ตอนสั่งซื้อ (ไม่ต้องสนตัวพิมพ์เล็กใหญ่)', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='โค้ด'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'ลดเป็นเปอร์เซ็นต์'), ('fixed', 'ลดเป็นจำนวนเงิน')], default='percent', max_length=8, verbose_name='ประเภทส่วนลด'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.PositiveIntegerField(help_text='ถ้าเลือก “ลดเป็นเปอร์เซ็นต์” ใส่ 20 = ลด 20% · ถ้าเลือก “ลดเป็นจำนวนเงิน” ใส่เป็นสตางค์ เช่น 5000 = ลด ฿50', verbose_name='ส่วนลด'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ปิดแล้วโค้ดใช้ไม่ได้ทันที ใช้กรณีโค้ดหลุด', verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='ใส่ 0 = ใช้ได้ไม่จำกัดจำนวนครั้ง', verbose_name='จำกัดจำนวนครั้ง'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_amount_satang',
            field=models.PositiveIntegerField(default=0, help_text='ราคาแผนต้องไม่ต่ำกว่านี้ถึงใช้โค้ดได้ ใส่เป็นสตางค์ · 0 = ไม่มีขั้นต่ำ', verbose_name='ยอดขั้นต่ำ (สตางค์)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='note',
            field=models.CharField(blank=True, help_text='ลูกค้าไม่เห็นข้อความนี้', max_length=200, verbose_name='บันทึกช่วยจำ'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='once_per_user',
            field=models.BooleanField(default=True, help_text='เปิดไว้ = คนเดิมใช้โค้ดนี้ซ้ำไม่ได้', verbose_name='หนึ่งคนใช้ได้ครั้งเดียว'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='ระบบนับให้เองเมื่อมีคนจ่ายเงินสำเร็จ ไม่ควรแก้มือ', verbose_name='ใช้ไปแล้ว (ครั้ง)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='เว้นว่าง = ใช้ได้ทันที', null=True, verbose_name='เริ่มใช้ได้'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='เว้นว่าง = ไม่มีวันหมดอายุ', null=True, verbose_name='ใช้ได้ถึง'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='doodee.coupon', verbose_name='คูปอง'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='doodee.order', verbose_name='คำสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='redeemed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ใช้เมื่อ'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='dailyactive',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='dailyactive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_active', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='firebaseidentity',
            name='firebase_uid',
            field=models.CharField(help_text='รหัสที่ Firebase ออกให้ตอนสมัคร ใช้ค้นหาผู้ใช้เวลามีปัญหาเรื่องล็อกอิน', max_length=128, unique=True, verbose_name='รหัสผู้ใช้ Firebase'),
        ),
        migrations.AlterField(
            model_name='firebaseidentity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_identity', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='doodee.coupon', verbose_name='คูปองที่ใช้'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สั่งซื้อเมื่อ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='THB', max_length=3, verbose_name='สกุลเงิน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_satang',
            field=models.PositiveIntegerField(default=0, verbose_name='ส่วนลด (สตางค์)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, help_text='เช่น เลขที่สลิปโอนเงิน หรือเหตุผลที่ยกเลิก', max_length=200, verbose_name='บันทึกช่วยจำ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='จ่ายเมื่อ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='doodee.plan', verbose_name='แผน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('manual', 'โอนเงิน (ยืนยันเอง)'), ('omise', 'Omise (PromptPay)')], default='manual', max_length=10, verbose_name='ช่องทางชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_charge_id',
            field=models.CharField(blank=True, help_text='รหัสอ้างอิงจาก Omise ใช้ตรวจสอบย้อนหลังเวลาเงินมีปัญหา', max_length=128, verbose_name='รหัสรายการจากผู้ให้บริการ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'จ่ายแล้ว'), ('failed', 'ล้มเหลว'), ('refunded', 'คืนเงินแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', help_text='อย่าแก้ช่องนี้มือเพื่อเปิดสิทธิ์ ให้ใช้ปุ่ม “ยืนยันการชำระเงิน” ด้านบนแทน มิฉะนั้นผู้ใช้จะไม่ได้สิทธิ์', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_satang',
            field=models.PositiveIntegerField(verbose_name='ราคาก่อนลด (สตางค์)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_satang',
            field=models.PositiveIntegerField(help_text='ราคาก่อนลด ลบ ส่วนลด · คอลัมน์ในตารางแปลงเป็นบาทให้แล้ว', verbose_name='ยอดที่ต้องจ่าย (สตางค์)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ซื้อ'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(help_text='รหัสภายในระบบ เช่น free, member, clinic ห้ามแก้หลังเปิดขายแล้ว เพราะสิทธิ์ของผู้ใช้ผูกกับค่านี้', max_length=32, unique=True, verbose_name='รหัสแผน'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='คำอธิบาย (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_th',
            field=models.CharField(blank=True, max_length=300, verbose_name='คำอธิบาย (ไทย)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='รหัสฟีเจอร์ที่จะติ๊กถูกในตารางราคาบนหน้าเว็บ', verbose_name='รายการฟีเจอร์'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='grants_group',
            field=models.CharField(blank=True, help_text='ชื่อกลุ่มที่ผู้ใช้จะถูกใส่เข้าไปเมื่อจ่ายเงินสำเร็จ เช่น pro_member เว้นว่างสำหรับแผนฟรี', max_length=64, verbose_name='กลุ่มสิทธิ์ที่ได้รับ'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('month', 'รายเดือน'), ('year', 'รายปี'), ('once', 'จ่ายครั้งเดียว')], default='month', max_length=8, verbose_name='รอบการเก็บเงิน'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ปิดแล้วแผนนี้จะหายจากหน้าราคาทันที คนที่ซื้อไปแล้วยังใช้ได้ตามปกติ', verbose_name='เปิดขาย'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=80, verbose_name='ชื่อแผน (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name_th',
            field=models.CharField(max_length=80, verbose_name='ชื่อแผน (ไทย)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_satang',
            field=models.PositiveIntegerField(default=0, help_text='กรอกเป็นสตางค์ ไม่ใช่บาท เช่น ฿149.00 ให้ใส่ 14900 (คอลัมน์ “ราคา” ในตารางแปลงเป็นบาทให้แล้ว)', verbose_name='ราคา (สตางค์)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='self_serve',
            field=models.BooleanField(default=True, help_text='ปิดไว้ = หน้าเว็บจะแสดงปุ่ม “ติดต่อทีมงาน” แทนปุ่มสั่งซื้อ (ใช้กับแผนคลินิกพาร์ทเนอร์)', verbose_name='ให้ซื้อเองได้'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='เลขน้อยอยู่ซ้าย', verbose_name='ลำดับการแสดง'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='อย่างน้อย 8 ตัวอักษร ใช้ซ้ำได้ไม่จำกัดจำนวนคน ถ้าโค้ดหลุดให้ปิด “เปิดใช้งาน” แทนการลบ', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='โค้ด'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='days',
            field=models.PositiveSmallIntegerField(default=7, help_text='นับจากวันที่กดใช้โค้ด ใส่ 0 = หมดอายุทันที (ใช้ทดสอบเท่านั้น)', verbose_name='ให้สิทธิ์กี่วัน'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='note',
            field=models.CharField(blank=True, help_text='เขียนไว้ว่าโค้ดนี้แจกใคร งานอะไร ผู้ใช้ไม่เห็นข้อความนี้', max_length=200, verbose_name='บันทึกช่วยจำ'),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='expires_at',
            field=models.DateTimeField(verbose_name='สิทธิ์หมดอายุ'),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='doodee.promocode', verbose_name='โค้ดรับสิทธิ์'),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='redeemed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ใช้เมื่อ'),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='age_band',
            field=models.CharField(choices=[('adult', '18 ปีขึ้นไป'), ('minor', 'ต่ำกว่า 18 ปี')], max_length=8, verbose_name='ช่วงอายุ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True, verbose_name='ผลวิเคราะห์'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ผู้ใช้ขอลบเมื่อ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='error_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='รหัสข้อผิดพลาด'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, verbose_name='ข้อความข้อผิดพลาด'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='expires_at',
            field=models.DateTimeField(help_text='ถึงเวลานี้แล้วภาพจะถูกลบอัตโนมัติ ผลวิเคราะห์ยังอยู่', verbose_name='หมดอายุ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='formula_version',
            field=models.CharField(default='2026.1', max_length=16, verbose_name='เวอร์ชันสูตรคำนวณ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='image_objects',
            field=models.JSONField(default=dict, verbose_name='ไฟล์ภาพ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='ข้อมูลตัวอย่างที่ระบบสร้างเอง ไม่ใช่คนจริง อย่านับรวมในรายงาน', verbose_name='เป็นข้อมูลตัวอย่าง'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ความคืบหน้า (%)'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='reference_age_band',
            field=models.CharField(default='18_35', max_length=16, verbose_name='ช่วงอายุกลุ่มอ้างอิง'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='reference_population',
            field=models.CharField(default='TH', max_length=8, verbose_name='ประชากรอ้างอิง'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='reference_profile',
            field=models.CharField(default='neutral', max_length=12, verbose_name='โปรไฟล์กลุ่มอ้างอิง'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_mode',
            field=models.CharField(choices=[('full', 'ครบ 7 มุม'), ('standard', 'หน้าตรงและด้านข้างสองข้าง'), ('fast', 'เร็ว 3 มุม')], default='full', max_length=16, verbose_name='โหมดการสแกน'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('queued', 'รอคิว'), ('processing', 'กำลังประมวลผล'), ('completed', 'เสร็จแล้ว'), ('failed', 'ล้มเหลว'), ('deletion_pending', 'รอลบ')], db_index=True, default='queued', max_length=24, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='after_object',
            field=models.CharField(blank=True, max_length=500, verbose_name='ไฟล์ภาพหลัง'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='before_object',
            field=models.CharField(blank=True, max_length=500, verbose_name='ไฟล์ภาพก่อน'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ผู้ใช้ขอลบเมื่อ'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='error_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='รหัสข้อผิดพลาด'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, verbose_name='ข้อความข้อผิดพลาด'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='หมดอายุ'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='measurements',
            field=models.JSONField(default=list, verbose_name='ค่าที่วัดได้'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='model_version',
            field=models.CharField(max_length=80, verbose_name='เวอร์ชันโมเดล'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='parameters',
            field=models.JSONField(default=dict, verbose_name='ค่าที่ใช้จำลอง'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='preset_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='รูปแบบที่เลือก'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ความคืบหน้า (%)'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='region',
            field=models.CharField(max_length=16, verbose_name='บริเวณ'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='related_procedures',
            field=models.JSONField(default=list, verbose_name='หัตถการที่เกี่ยวข้อง'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='doodee.scan', verbose_name='การสแกน'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='selections',
            field=models.JSONField(default=list, verbose_name='รายการที่เลือกทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='source_view',
            field=models.CharField(blank=True, max_length=24, verbose_name='มุมภาพต้นทาง'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('queued', 'รอคิว'), ('processing', 'กำลังประมวลผล'), ('completed', 'เสร็จแล้ว'), ('failed', 'ล้มเหลว'), ('deletion_pending', 'รอลบ')], db_index=True, default='queued', max_length=24, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='simulationpreviewusage',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ใช้ไปแล้ว (ครั้ง)'),
        ),
        migrations.AlterField(
            model_name='simulationpreviewusage',
            name='period',
            field=models.DateField(help_text='วันที่ 1 ของเดือนที่นับโควตานี้', verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='simulationpreviewusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_preview_usage', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ยกเลิกเมื่อ'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เริ่มเมื่อ'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(help_text='ถึงวันนี้แล้วระบบจะถอดสิทธิ์ให้เองตอนผู้ใช้เปิดแอป ไม่ต้องรอ cron', verbose_name='สิทธิ์ถึงวันที่'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='doodee.order', verbose_name='คำสั่งซื้อที่เป็นต้นทาง'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='doodee.plan', verbose_name='แผน'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'ใช้งานอยู่'), ('cancelled', 'ยกเลิกแล้ว'), ('expired', 'หมดอายุ')], default='active', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
    ]
