# Generated by Django 5.2.17 on 2026-08-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0015_alter_chatconversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.TextField(blank=True, help_text='เขียนว่าอยากให้ AI พูดจาแบบไหน เช่น สั้น เป็นกันเอง เรียกผู้ใช้ว่า “คุณ” · กฎความปลอดภัย (ห้ามตัดสินความสวย ไม่ใช่คำวินิจฉัยแพทย์ ห้ามรับประกันผล) ระบบต่อท้ายให้เสมอและลบไม่ได้ · เว้นว่างได้', verbose_name='บุคลิกและวิธีตอบ')),
                ('model', models.CharField(choices=[('claude-opus-5', 'Opus 5 — ฉลาดที่สุด แพงที่สุด'), ('claude-sonnet-5', 'Sonnet 5 — สมดุล'), ('claude-haiku-4-5-20251001', 'Haiku 4.5 — เร็วและถูกที่สุด')], default='claude-opus-5', help_text='เปลี่ยนแล้วมีผลกับข้อความถัดไปทันที ไม่ต้อง deploy', max_length=48, verbose_name='โมเดล')),
                ('effort', models.CharField(choices=[('low', 'ต่ำ — ตอบเร็ว ประหยัด'), ('medium', 'กลาง'), ('high', 'สูง — คิดละเอียด ช้าและแพงขึ้น')], default='low', max_length=8, verbose_name='ระดับการคิด')),
                ('max_tokens', models.PositiveIntegerField(default=1500, help_text='ประมาณ 1,500 โทเค็น ≈ 3-4 ย่อหน้า · ยิ่งมากยิ่งจ่ายแพงต่อคำตอบ', verbose_name='ความยาวคำตอบสูงสุด (โทเค็น)')),
                ('free_turns', models.PositiveIntegerField(default=5, help_text='นับเฉพาะคำถามที่พิมพ์เอง คำถามสำเร็จรูปไม่กินโควตา', verbose_name='โควตาแผนฟรี (ครั้ง/เดือน)')),
                ('paid_turns', models.PositiveIntegerField(default=300, help_text='เพดานกันบัญชีถูกยึดแล้วยิงจนงบหมด ไม่ใช่การจำกัดการใช้งานปกติ', verbose_name='โควตาแผนจ่ายเงิน (ครั้ง/เดือน)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'ตั้งค่า AI แชท',
                'verbose_name_plural': 'ตั้งค่า AI แชท',
            },
        ),
        migrations.CreateModel(
            name='ChatTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ผูกกับสูตรคำนวณคำตอบในโค้ด แก้ไม่ได้', max_length=32, unique=True, verbose_name='รหัสหัวข้อ')),
                ('label_th', models.CharField(max_length=120, verbose_name='คำถาม (ไทย)')),
                ('label_en', models.CharField(max_length=160, verbose_name='คำถาม (อังกฤษ)')),
                ('is_active', models.BooleanField(default=True, help_text='ปิดแล้วปุ่มนี้จะหายจากหน้าแชททันที', verbose_name='แสดงบนหน้าแชท')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='เลขน้อยอยู่ก่อน', verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'คำถามสำเร็จรูปในแชท',
                'verbose_name_plural': 'คำถามสำเร็จรูปในแชท',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
