# Generated by Django 5.2.17 on 2026-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0017_seed_chat_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsetting',
            name='base_url',
            field=models.CharField(blank=True, help_text='Groq: https://api.groq.com/openai/v1 — OpenRouter: https://openrouter.ai/api/v1 — Ollama บนเครื่องเดียวกัน: http://host.docker.internal:11434/v1 · เว้นว่างเมื่อใช้ Anthropic', max_length=200, verbose_name='ที่อยู่ API (เฉพาะ OpenAI-compatible)'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude) — สำหรับใช้งานจริง'), ('openai', 'OpenAI-compatible (Groq / OpenRouter / Ollama) — สำหรับทดสอบ')], default='anthropic', help_text='คีย์ของแต่ละเจ้าเก็บใน .env ไม่ได้เก็บในฐานข้อมูล — Anthropic ใช้ ANTHROPIC_API_KEY · เจ้าอื่นใช้ CHAT_API_KEY (Ollama ไม่ต้องใช้คีย์)', max_length=16, verbose_name='ผู้ให้บริการ'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='model',
            field=models.CharField(default='claude-opus-5', help_text='Anthropic: claude-opus-5 · claude-sonnet-5 · claude-haiku-4-5-20251001 — Groq: llama-3.3-70b-versatile — OpenRouter: ใส่ชื่อที่ลงท้าย :free — Ollama: llama3.2 · เปลี่ยนแล้วมีผลกับข้อความถัดไปทันที ไม่ต้อง deploy', max_length=96, verbose_name='โมเดล'),
        ),
    ]
