# Generated by Django 5.2.17 on 2026-08-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0018_chatsetting_base_url_chatsetting_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ใช้อ้างอิงในโค้ดและเก็บไว้กับห้องแชท แก้ไม่ได้', max_length=32, unique=True, verbose_name='รหัสโรล')),
                ('label_th', models.CharField(max_length=60, verbose_name='ชื่อโรล (ไทย)')),
                ('label_en', models.CharField(max_length=80, verbose_name='ชื่อโรล (อังกฤษ)')),
                ('description_th', models.CharField(blank=True, help_text='ข้อความใต้ชื่อโรลบนหน้าแชท บอกผู้ใช้ว่าเลือกแล้วจะได้คำตอบแบบไหน', max_length=160, verbose_name='คำอธิบายสั้น (ไทย)')),
                ('description_en', models.CharField(blank=True, max_length=200, verbose_name='คำอธิบายสั้น (อังกฤษ)')),
                ('persona', models.TextField(help_text='เขียนว่าโรลนี้พูดยังไง · กฎความปลอดภัยระบบต่อท้ายให้เสมอและลบไม่ได้ รวมถึงกฎที่ว่าน้ำเสียงเปลี่ยนได้แค่วิธีพูด ไม่เปลี่ยนสิ่งที่พูดได้', verbose_name='น้ำเสียง')),
                ('is_active', models.BooleanField(default=True, help_text='ปิดแล้วปุ่มนี้จะหายจากหน้าแชททันที', verbose_name='เปิดใช้งาน')),
                ('is_default', models.BooleanField(default=False, help_text='โรลที่ห้องใหม่ใช้เมื่อผู้ใช้ไม่ได้เลือก · ควรเปิดไว้ตัวเดียว', verbose_name='เป็นค่าเริ่มต้น')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='เลขน้อยอยู่ก่อน', verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'โรลของ AI แชท',
                'verbose_name_plural': 'โรลของ AI แชท',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='role',
            field=models.CharField(blank=True, help_text='เลือกตอนเปิดห้อง เปลี่ยนกลางห้องไม่ได้ เพราะจะทำให้ prompt cache พังทุกเทิร์น', max_length=32, verbose_name='โรลที่ใช้'),
        ),
    ]
