# Generated by Django 5.2.17 on 2026-08-22 01:52

"""Bank details and the payout queue.

The referral reward became real money the inviter can withdraw, so two things arrive: somewhere to
send it, and a record of an operator deciding to send it.

`PayoutAccount.number_encrypted` is the only column in the product holding a customer bank detail,
and it holds ciphertext. The key is in the environment, never here — see `payout.py`.

Nothing in this migration can move money. There is no payout rail; an admin makes the transfer by
hand and records the reference, which is `Order.Provider.MANUAL` run backwards.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0026_site_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='kind',
            field=models.CharField(choices=[('referral_reward', 'รางวัลชวนเพื่อน'), ('order_spend', 'ใช้จ่ายค่าสมาชิก'), ('withdrawal', 'ขอถอนเงิน'), ('admin_adjust', 'แอดมินปรับยอด'), ('clawback', 'เรียกคืนรางวัล'), ('refund', 'คืนเครดิต')], max_length=16, verbose_name='ประเภท'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('renewal_due', 'ใกล้ครบกำหนดต่ออายุ'), ('renewal_lapsed', 'สมาชิกหมดอายุแล้ว'), ('referral_reward', 'ได้รางวัลชวนเพื่อน'), ('referral_joined', 'เพื่อนสมัครแล้ว'), ('coupon_granted', 'ได้รับคูปอง'), ('order_paid', 'ยืนยันการชำระเงินแล้ว'), ('withdrawal_paid', 'โอนเงินที่ขอถอนแล้ว'), ('withdrawal_rejected', 'คำขอถอนเงินไม่ผ่าน')], max_length=20, verbose_name='ประเภท'),
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('promptpay', 'พร้อมเพย์'), ('bank', 'บัญชีธนาคาร')], default='promptpay', max_length=10, verbose_name='ช่องทางรับเงิน')),
                ('bank', models.CharField(blank=True, help_text='เว้นว่างเมื่อรับเงินทางพร้อมเพย์', max_length=40, verbose_name='ธนาคาร')),
                ('account_name', models.CharField(help_text='ต้องตรงกับชื่อในบัญชีจริง ไม่งั้นโอนไม่ผ่าน', max_length=120, verbose_name='ชื่อบัญชี')),
                ('number_encrypted', models.BinaryField(verbose_name='เลขบัญชี (เข้ารหัสไว้)')),
                ('number_last4', models.CharField(help_text='เก็บไว้แบบอ่านได้ตัวเดียว เพื่อให้ผู้ใช้จำบัญชีตัวเองได้โดยไม่ต้องถอดรหัส', max_length=4, verbose_name='เลขท้าย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เพิ่มเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บัญชีรับเงิน',
                'verbose_name_plural': 'บัญชีรับเงิน',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_satang', models.PositiveIntegerField(help_text='คอลัมน์ในตารางแปลงเป็นบาทให้แล้ว', verbose_name='จำนวนที่ขอถอน (สตางค์)')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว รอโอน'), ('paid', 'โอนแล้ว'), ('rejected', 'ไม่อนุมัติ'), ('cancelled', 'ผู้ใช้ยกเลิก')], default='pending', help_text='อย่าแก้ช่องนี้มือ ให้ใช้ปุ่มด้านบน มิฉะนั้นเครดิตกับสถานะจะไม่ตรงกัน', max_length=10, verbose_name='สถานะ')),
                ('destination', models.JSONField(default=dict, help_text='สำเนาข้อมูลบัญชี ณ เวลาที่กดขอถอน · ถ้าผู้ใช้แก้บัญชีทีหลัง รายการนี้ไม่เปลี่ยนตาม', verbose_name='ปลายทางตอนที่ขอถอน')),
                ('reference', models.CharField(blank=True, help_text='เลขอ้างอิงหรือเลขที่สลิป · ต้องกรอกก่อนถึงจะบันทึกว่าโอนแล้วได้', max_length=120, verbose_name='อ้างอิงการโอน')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='บันทึกช่วยจำ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='ตรวจสอบเมื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ขอเมื่อ')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='โอนเมื่อ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตรวจสอบ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอถอน')),
            ],
            options={
                'verbose_name': 'คำขอถอนเงิน',
                'verbose_name_plural': 'คำขอถอนเงิน',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='doodee_with_status_902f98_idx')],
            },
        ),
    ]
