# Generated by Django 5.2.17 on 2026-08-27 12:34
#
# The three pieces of the marketing report. No data migration: `capture_method` is blank by
# design, so every existing scan correctly reads as "ไม่ระบุ" rather than being guessed at.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0027_payout_account_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='capture_method',
            field=models.CharField(blank=True, choices=[('web_camera', 'กล้องบนเว็บ'), ('mobile_camera', 'กล้องบนแอปมือถือ')], default='', max_length=16, verbose_name='วิธีถ่ายภาพ'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('source', models.CharField(default='direct', max_length=32, verbose_name='แหล่งที่มา')),
                ('medium', models.CharField(default='direct', max_length=32, verbose_name='ช่องทาง')),
                ('campaign', models.CharField(default='direct', max_length=32, verbose_name='แคมเปญ')),
                ('landing_path', models.CharField(default='/', max_length=32, verbose_name='หน้าที่เข้ามา')),
                ('device', models.CharField(choices=[('mobile', 'มือถือ'), ('desktop', 'คอมพิวเตอร์')], default='desktop', max_length=8, verbose_name='อุปกรณ์')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้ง')),
            ],
            options={
                'verbose_name': 'ผู้เข้าชมเว็บ',
                'verbose_name_plural': 'ผู้เข้าชมเว็บ',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['date'], name='doodee_visi_date_9b859f_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'source', 'medium', 'campaign', 'landing_path', 'device'), name='unique_visit_bucket')],
            },
        ),
        migrations.CreateModel(
            name='UserAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='direct', max_length=32, verbose_name='แหล่งที่มา')),
                ('medium', models.CharField(default='direct', max_length=32, verbose_name='ช่องทาง')),
                ('campaign', models.CharField(default='direct', max_length=32, verbose_name='แคมเปญ')),
                ('landing_path', models.CharField(default='/', max_length=32, verbose_name='หน้าที่เข้ามา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ที่มาของผู้ใช้',
                'verbose_name_plural': 'ที่มาของผู้ใช้',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source'], name='doodee_user_source_2658bd_idx'), models.Index(fields=['campaign'], name='doodee_user_campaig_5e62ec_idx')],
            },
        ),
    ]
