# Generated by Django 5.2.17 on 2026-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0030_chatsetting_gemini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentevent',
            name='purpose',
            field=models.CharField(choices=[('analysis', 'วิเคราะห์ใบหน้า'), ('storage', 'เก็บภาพและประวัติ'), ('simulation', 'จำลองผลในเครื่อง'), ('chat', 'ส่งตัวเลขให้โมเดลภายนอก (แชท)'), ('skin_vision', 'ส่งภาพใบหน้าให้โมเดลภายนอก (วิเคราะห์ผิว)')], max_length=16, verbose_name='ยินยอมเรื่องอะไร'),
        ),
    ]
