"""ทางเข้าใหม่: อัปโหลดรูปในหน้าสแกน

Two new choices, no data to move.

`Scan.CaptureMethod.UPLOAD` is the member `models.py` has been reserving in a comment since the
capture-method field was added — "add it the day an upload path ships" — and this is that day.
Existing rows are untouched: every scan recorded so far did come from a camera, so nothing needs
reclassifying, and the blank default keeps meaning "recorded before anyone was asked".

`ConsentEvent.Purpose.PHOTO_OWNER` is the confirmation that an uploaded photograph is of the person
uploading it. `views._scan_fields` refuses an upload without one, so no scan can exist with the new
capture method and no matching row — but only from now on, which is the only guarantee a migration
can honestly make.
"""

# Generated by Django 5.2.17 on 2026-08-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0032_plus_quotas_from_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentevent',
            name='purpose',
            field=models.CharField(choices=[('analysis', 'วิเคราะห์ใบหน้า'), ('storage', 'เก็บภาพและประวัติ'), ('simulation', 'จำลองผลในเครื่อง'), ('chat', 'ส่งตัวเลขให้โมเดลภายนอก (แชท)'), ('skin_vision', 'ส่งภาพใบหน้าให้โมเดลภายนอก (วิเคราะห์ผิว)'), ('photo_owner', 'ยืนยันว่าภาพที่อัปโหลดเป็นใบหน้าของตนเอง')], max_length=16, verbose_name='ยินยอมเรื่องอะไร'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='capture_method',
            field=models.CharField(blank=True, choices=[('web_camera', 'กล้องบนเว็บ'), ('mobile_camera', 'กล้องบนแอปมือถือ'), ('upload', 'อัปโหลดรูป')], default='', max_length=16, verbose_name='วิธีถ่ายภาพ'),
        ),
    ]
