# Generated by Django 5.2.17 on 2026-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0033_upload_capture_and_photo_owner_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='model',
            field=models.CharField(default='gemini-2.5-flash', help_text='Gemini: gemini-2.5-flash · gemini-2.0-flash — Anthropic: claude-opus-5 · claude-sonnet-5 · claude-haiku-4-5-20251001 — Groq: openai/gpt-oss-120b — OpenRouter: ใส่ชื่อที่ลงท้าย :free — Ollama: llama3.2 · เปลี่ยนแล้วมีผลกับข้อความถัดไปทันที ไม่ต้อง deploy', max_length=96, verbose_name='โมเดล'),
        ),
    ]
