# Generated by Django 5.2.17 on 2026-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0034_alter_chatsetting_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_mode',
            field=models.CharField(choices=[('full', 'ครบ 7 มุม'), ('standard', 'หน้าตรงและด้านข้างสองข้าง'), ('fast', 'เร็ว 3 มุม'), ('skin', 'วิเคราะห์ผิว (ระยะใกล้)')], default='full', max_length=16, verbose_name='โหมดการสแกน'),
        ),
    ]
