# Generated by Django 5.2.17 on 2026-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0035_alter_scan_scan_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='view_objects',
            field=models.JSONField(blank=True, default=dict, verbose_name='ไฟล์ภาพรายมุม'),
        ),
    ]
