# Generated by Django 5.2.17 on 2026-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0036_simulation_view_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='slip_contact',
            field=models.CharField(blank=True, help_text='เช่น LINE @doodee หรืออีเมล · ว่างอยู่ = ขายไม่ได้ เพราะลูกค้าไม่รู้จะส่งหลักฐานไปทางไหน', max_length=120, verbose_name='ส่งสลิปมาที่'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='transfer_account_name',
            field=models.CharField(blank=True, help_text='ชื่อที่ลูกค้าจะเห็นตอนโอน ต้องตรงกับบัญชีจริง', max_length=120, verbose_name='ชื่อบัญชีที่รับโอน'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='transfer_account_number',
            field=models.CharField(blank=True, help_text='ลูกค้าเห็นเลขนี้เต็ม ๆ เพราะต้องโอนเข้ามา · ว่างอยู่ = ขายไม่ได้ ระบบจะปฏิเสธคำสั่งซื้อ', max_length=40, verbose_name='เลขบัญชี / พร้อมเพย์'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='transfer_bank',
            field=models.CharField(blank=True, help_text='เช่น กสิกรไทย · เว้นว่างได้ถ้ารับเฉพาะพร้อมเพย์', max_length=60, verbose_name='ธนาคารที่รับโอน'),
        ),
    ]
