# Generated by Django 5.2.17 on 2026-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0037_sitesetting_slip_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'จ่ายแล้ว'), ('failed', 'ล้มเหลว'), ('refunded', 'คืนเงินแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', help_text='แก้ช่องนี้เองไม่ได้ · เปิดสิทธิ์โดยติ๊กคำสั่งซื้อในหน้ารายการ แล้วเลือก "ยืนยันการชำระเงิน — เปิดสิทธิ์ให้ผู้ใช้" จากเมนู Action', max_length=10, verbose_name='สถานะ'),
        ),
    ]
