# Generated by Django 5.2.17 on 2026-09-02 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0038_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(help_text='รหัสจากการล็อกอินอีกช่องทางของคนเดิม เช่น สมัครด้วยอีเมลแล้วมาล็อกอินด้วย Google', max_length=128, unique=True, verbose_name='รหัสผู้ใช้ Firebase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ผูกเมื่อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_aliases', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บัญชี Firebase ที่ผูกเพิ่ม',
                'verbose_name_plural': 'บัญชี Firebase ที่ผูกเพิ่ม',
                'ordering': ('-created_at',),
            },
        ),
    ]
