# Generated by Django 5.2.17 on 2026-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodee', '0039_firebasealias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, help_text='เช่น เลขที่สลิปโอนเงิน หรือเหตุผลที่ยกเลิก · กรอกจากหน้ารายการได้เลย แต่ต้องกด Save ก่อน แล้วค่อยติ๊กเลือกแล้วสั่ง "ยืนยันการชำระเงิน" — ถ้าสั่ง Action ก่อน สิ่งที่พิมพ์ค้างไว้จะหาย', max_length=200, verbose_name='บันทึกช่วยจำ'),
        ),
    ]
